### PR TITLE
fix invalid yaml in resource utilities README

### PR DESCRIPTION
**Pull request by vsoch**
Problem: one of the yaml examples in resource/utilities/README is invalid - it is missing a with: header for a section (and does not load). This fixes it.

### CODE REVIEW

**Review by jameshcorbett — APPROVED** [review]
LGTM but would you mind changing the commit title to "doc: fix ..."

Not sure why the commit validator isn't running...

**Comment by vsoch** [comment]
Fixed! Maybe he's on strike?

**Comment by grondo** [comment]
The pr-validator was skipped because this PR is proposed from a branch within the current repo instead of a fork. @vsoch we typically do not push branches to the upstream repos and instead propose PRs from personal forks. (No need to move this particular branch though, not a big deal!)

**Comment by vsoch** [comment]
What was wrong with my commit? I updated as you asked?

**Comment by jameshcorbett** [comment]
Oh yeah, I force-pushed because I rebased on top of master in order to merge. Sorry, should have told you.

**Comment by vsoch** [comment]
ah ok, thanks! This PR wins the award for the most changes and developer time for the smallest amount of change I think! :laughing: 

> The pr-validator was skipped because this PR is proposed from a branch within the current repo instead of a fork. @vsoch we typically do not push branches to the upstream repos and instead propose PRs from personal forks. (No need to move this particular branch though, not a big deal!)

Sorry about that @grondo - I opened in the GitHub editor and thought since that was the default it would be OK - won't do next time.

**Comment by grondo** [comment]
> I opened in the GitHub editor and thought since that was the default it would be OK - won't do next time.

No problem! Thanks!

**Comment by grondo** [comment]
I restarted the el7 builder since it seemed to hit some spurious test failures (obviously not caused by this PR!)

**Comment by trws** [comment]
I just bounced that one again, and it seemed to pass, but the mergify end failed.  Have you seen anything like this @grondo?

**Comment by grondo** [comment]
I think we might have to manually merge this one since it is from a branch in this repo instead of a fork, so not all the ci checks were able to run. We can try 

@mergifyio refresh

First though.

**Comment by grondo** [comment]
I'll just force github to rebase first.

**Comment by grondo** [comment]
Since obviously tests will pass, I'll manually merge (no sense waiting for the tests again)

**Comment by trws** [comment]
Cool, thanks @grondo!

**Comment by vsoch** [comment]
Sorry didn't mean to cause so much pain here! :sob: Thanks for the support!

**Comment by grondo** [comment]
No problem at all!

**Pull request merged**
