### PR TITLE
Sched install improvements

### PR DESCRIPTION
**Pull request by lipari**
This PR addresses the items listed in [Issue 125](https://github.com/flux-framework/flux-sched/issues/125).  @garlick, let me know if you see anything I missed w/r/t this issue.  The changes needed to address [Issue 140](https://github.com/flux-framework/flux-sched/issues/140), as well as the work to cull sched's installed products to just the essential libraries, can be in a separate PR.

### CODE REVIEW

**Comment by garlick** [comment]
Looks good - I'll give it a test when I get a chance.  I'm being called home at the moment though.

**Comment by dongahn** [comment]
Looks good to me as well. We'll see if @garlick can find anything from his testing.

**Comment by garlick** [comment]
Sorry for the delay.  I am seeing some intermittent failures of the jsc and rs2rank tests on this branch and oops, maybe on master too, so probably not related to this PR.  Just trying to get a sensible bug report open before proceeding with tests

**Comment by lipari** [comment]
Just for reference, here is the issue for this bug:  https://github.com/flux-framework/flux-sched/issues/134.  I thought the changes to make `flux module load` return only when loaded was the fix.

**Comment by garlick** [comment]
It looks like modules are named properly, are installed to the correct locations, and installed modules can be found with without setting FLUX_MODULEPATH e.g.
```
#!/bin/bash
prefix=$HOME/local
module load python python-pycparser python-cffi mvapich2-gnu-shmem
export PATH=$prefix/bin:$PATH
flux start -o,--setattr=log-stderr-level=7 flux module load sched plugin=sched.fcfs
```
logs look like this
```
[1458061994.096128] broker.info[0]: nodeset: 0 (complete)
[1458061994.096147] broker.info[0]: Run level 1 starting
[1458061994.128457] broker.info[0]: insmod barrier
[1458061994.161462] broker.info[0]: insmod content-sqlite
[1458061994.163127] broker.debug[0]: content backing store: enabled content-sqlite
[1458061994.194987] broker.info[0]: insmod kvs
[1458061994.226352] broker.info[0]: insmod live
[1458061994.295002] broker.info[0]: insmod mecho
[1458061994.311096] broker.info[0]: insmod resource-hwloc
[1458061994.343368] broker.info[0]: insmod job
[1458061994.375390] broker.info[0]: insmod wrexec
[1458061994.428546] resource-hwloc.debug[0]: loaded
[1458061994.429842] broker.info[0]: Run level 1 Exited (rc=0)
[1458061994.429849] broker.info[0]: Run level 2 starting
[1458061994.462157] broker.info[0]: insmod sched
[1458061994.462879] sched.info[0]: sched comms module starting
[1458061994.466641] sched.debug[0]: loaded: sched.fcfs
[1458061994.466669] sched.info[0]: sched.fcfs plugin loaded
[1458061994.466681] sched.debug[0]: LUA_PATH /home/garlick/proj/flux-core/src/bindings/lua/?.lua;/home/garlick/local/share/lua/5.1/?.lua;;;
[1458061994.466693] sched.debug[0]: LUA_CPATH /home/garlick/proj/flux-core/src/bindings/lua/?.so;/home/garlick/local/lib64/lua/5.1/?.so;;;
[1458061994.470670] sched.info[0]: resources loaded
[1458061994.471279] sched.info[0]: events registered
[1458061994.471936] broker.info[0]: Run level 2 Exited (rc=0)
[1458061994.472030] broker.info[0]: Run level 3 starting
[1458061994.474602] broker.info[0]: shutdown in 0.500s: run level 2 Exited
[1458061994.472631] content-sqlite.debug[0]: broker shutdown in progress
[1458061994.493231] broker.info[0]: rmmod wrexec
[1458061994.493324] broker.info[0]: module wrexec exited
[1458061994.510436] broker.info[0]: rmmod job
[1458061994.510498] job.info[0]: got request job.shutdown
[1458061994.510664] broker.info[0]: module job exited
[1458061994.527463] broker.info[0]: rmmod mecho
[1458061994.527548] broker.info[0]: module mecho exited
[1458061994.544045] broker.info[0]: rmmod resource-hwloc
[1458061994.544493] broker.info[0]: module resource-hwloc exited
[1458061994.561327] broker.info[0]: rmmod live
[1458061994.561464] broker.info[0]: module live exited
[1458061994.577910] broker.info[0]: rmmod kvs
[1458061994.578066] broker.info[0]: module kvs exited
[1458061994.594447] broker.info[0]: rmmod barrier
[1458061994.594589] broker.info[0]: module barrier exited
[1458061994.610878] broker.info[0]: rmmod content-sqlite
[1458061994.610948] content-sqlite.debug[0]: shutdown: begin
[1458061994.611130] broker.debug[0]: content backing store: disabled content-sqlite
[1458061994.611207] content-sqlite.info[0]: shutdown: skipping
[1458061994.611358] broker.info[0]: module content-sqlite exited
[1458061994.612685] broker.info[0]: Run level 3 Exited (rc=0)
```

**Comment by garlick** [comment]
One thought though: could we drop the "srv" suffix from the sched module?  That convention was dropped quite a while ago.

**Comment by lipari** [comment]
> One thought though: could we drop the "srv" suffix from the sched module? That convention was dropped quite a while ago.

Ok.  new push momentarily with schedsrv.[ch] renamed to sched.[ch]

**Comment by lipari** [comment]
Well... I'm running into some include issues during compile time which need to be carefully navigated.  "sched.h" is a popular file name.  Do we want to change schedsrv to fluxsched?

**Comment by garlick** [comment]
I'd go with "sched" and try to run down why a different sched is being included.  Maybe do a make with V=1 and see what -I options are being passed to the compiler?  -I. should be first.

**Comment by garlick** [comment]
One thing to watch out for: /usr/include/sched defines _SCHED_H so don't use that to defeat multiple inclusion of the flux one.  (use maybe _FLUX_SCHED_H)

**Comment by lipari** [comment]
No go.  /usr/include/czmq/czmq_prelude.h picks up flux-sched's sched.h instead of /usr/include/sched.h.  I guess I could qualify sched.h's location like '#include "sched/sched.h"`, but that would mean doing the same for resrc.h, resrc_tree.h, etc.

**Comment by garlick** [comment]
Part of what makes that tricky is it is an installed header file.  Does it need to be?  It seems like the types it defines are only used in schedsrv.c?

If it can be made local only, then just include it with the path relative to ${top_srcdir} as you suggested.

**Comment by garlick** [comment]
Er, except czmq will still pick it up there if it's named "sched.h".  So maybe it does need a rename.

**Comment by lipari** [comment]
>  So maybe it does need a rename.

Here are some ideas.  Any preference?
* scheduler
* schedbase
* schedmod
* <write-in candidate>

**Comment by garlick** [comment]
We're just talking about the header file, and an internal one right?  No preference.

**Comment by lipari** [comment]
> One thought though: could we drop the "srv" suffix from the sched module? That convention was dropped quite a while ago.

New push replaces schedsrv with sched.

**Comment by garlick** [comment]
OK, sorry that was a pain.  I ACK this PR and can push the button if you want me to.

**Comment by lipari** [comment]
NP.  Given that this work addresses an issue you submitted, go ahead and push the button.

**Pull request merged**
