### PR TITLE
sim: Fix easy-backfilling test case

### PR DESCRIPTION
**Pull request by SteVwonder**
Also improves error checking and logging of the simulator's KVS operations

Pre-requisites: https://github.com/flux-framework/flux-core/pull/872 must be merged first

Fixes: #214

### CODE REVIEW

**Comment by SteVwonder** [comment]
Apparently I forgot to rebase this onto the latest flux-sched,  I will do that once flux-framework/flux-core#872 is merged into flux-core, since Travis is going to fail anyways without that.

**Comment by SteVwonder** [comment]
I also didn't notice the conversation in #201 until now.  I need to re-add the `kvs_get_dir` after the `kvs_commit`.

**Comment by grondo** [comment]
@SteVwonder -- flux-framework/flux-core#872 has now been merged.

**Comment by dongahn** [comment]
Kicked Travis again.

**Comment by lipari** [comment]
Thank you @SteVwonder!  Merging...

**Comment by grondo** [comment]
> I also didn't notice the conversation in #201 until now. I need to re-add the kvs_get_dir after the kvs_commit.

Did that comment still need to be addressed?

**Comment by SteVwonder** [comment]
@grondo: yeah, I'm submitting a new PR to take care of that (I also realized that I accidentally left a debug print in the t2002-easy.t test script).  Should be up in ~15 minutes.

**Comment by lipari** [comment]
Sorry for jumping the gun.  Any philosophical objections to resetting the commit back to 26aa190615ff5a5885cf69b6f1ca716f4b04eb43

**Comment by SteVwonder** [comment]
@lipari: no worries.

If you want to avoid rolling back, we can just add a fixup commit on top.  I have no preference either way though, I defer to others on this one.

Also give me ~30 more minutes for the fixup, the fcfs and easy test scripts need a bit of cleaning up.  I'm switching them over to using the flux-waitjob as opposed to my hacky one-liner.

**Comment by grondo** [comment]
Since it didn't break the build or tests I don't think it is a big deal to have any necessary fixes put on top (my 2c)

**Pull request merged**
