### PR TITLE
Globally rename whitelist to allowlist

### LINKED ISSUE #669: Use allowlist instead of whitelist
From https://github.com/flux-framework/flux-sched/pull/663#discussion_r438358179

### PR DESCRIPTION
**Pull request by chu11**
This was done via simple search & replace, nothing more than that.

Fixes #669

### CODE REVIEW

**Comment by chu11** [comment]
strange, all the travis tests passed, but somehow the CI wasn't notified they completed.  restarted them all to see if that kicks it this time.

**Comment by dongahn** [comment]
LGTM! Thank you for tackling this @chu11. I will add MWP label.

**Comment by chu11** [comment]
@Mergifyio rebase

**Comment by chu11** [comment]
@dongahn I think you need to approve :-)

**Pull request merged**
