### PR TITLE
Issue 101

### PR DESCRIPTION
**Pull request by lipari**
Address [Issue 101](https://github.com/flux-framework/flux-sched/issues/101) by:
* support multiple job allocations per resource
* support a request for exclusive access to a resource

### CODE REVIEW

**Comment by dongahn** [comment]
@lipari: Thank you for the PR. 

At first glance, perhaps three things can help reviewing this PR to begin with.

1. If you agree commit [c5c6ccb](https://github.com/lipari/flux-sched/commit/c5c6ccb643b918cdd630c7768fe2f77951b728fd) is orthogonal to [cc3b0aa](https://github.com/lipari/flux-sched/commit/cc3b0aa4d0b61942d9b7b34ce4f7947b2ba6b130), perhaps each commit in this PR can be split into two indepedent PRs.

2. For [c5c6ccb](https://github.com/lipari/flux-sched/commit/c5c6ccb643b918cdd630c7768fe2f77951b728fd), can you please split the commit into at least two commits: one for the main change and the other for tests. 

3. Also for for [c5c6ccb](https://github.com/lipari/flux-sched/commit/c5c6ccb643b918cdd630c7768fe2f77951b728fd), would it be possible to add some end-to-end sharness testing to show the utility and correctness of the changes? This might involve changes to flux-submit itself and perhaps hard to do, but ideally these changes are all belonging to the same PR?

**Comment by lipari** [comment]
> If you agree commit c5c6ccb is orthogonal to cc3b0aa, perhaps each commit in this PR can be split into two indepedent PRs.

Will do.

> For c5c6ccb, can you please split the commit into at least two commits: one for the main change and the other for tests.

I believe you meant https://github.com/lipari/flux-sched/commit/cc3b0aa4d0b61942d9b7b34ce4f7947b2ba6b130.  There were no changes to the tests in the https://github.com/lipari/flux-sched/commit/c5c6ccb643b918cdd630c7768fe2f77951b728fd commit.  While I can certainly comply, I favor committing code changes that will build and pass the tests.  This allows us to use `git bisect`.  If I create separate commits, the first commit will never build.

> Also for for c5c6ccb, would it be possible to add some end-to-end sharness testing to show the utility and correctness of the changes? This might involve changes to flux-submit itself and perhaps hard to do, but ideally these changes are all belonging to the same PR?

I can do that as well.  However, I deliberately disabled the resource sharing functionality so that the existing fcfs and backfill tests would succeed.  My intent is to submit a later PR that activates resource sharing and includes tests for both exclusive and sharing scenarios.  However, I'm weeks away from delivering that.  I'd like to see these changes merged for now and give the new code some real-world exposure.  However, if you want to wait until the tests are done, then that's fine.

**Comment by dongahn** [comment]
> Will do.

Thanks.

> I believe you meant cc3b0aa. There were no changes to the tests in the c5c6ccb commit. 

@lipari: Sorry. Yes you are right it is cc3b0aa.

> While I can certainly comply, I favor committing code changes that will build and pass the tests. This allows us to use git bisect. If I create separate commits, the first commit will never build.

@lipari: I didn't realize the new change breaks the old test. In this case, yes I agree that the test change should stay with the interface change. 

> I can do that as well. However, I deliberately disabled the resource sharing functionality so that the existing fcfs and backfill tests would succeed. My intent is to submit a later PR that activates resource sharing and includes tests for both exclusive and sharing scenarios. However, I'm weeks away from delivering that. I'd like to see these changes merged for now and give the new code some real-world exposure. However, if you want to wait until the tests are done, then that's fine.

OK. Perhaps I should then merge this in. I was a bit worried about this support because as I am developing test cases, I see a matrix of many different cases -- essentially a cross-product between {hwloc reader mode, resrc mode, resrc emulator mode} and {single broker per node, multiple brokers per node with shared management, multiple brokers per node managing non-overlapping partition on a node}. And ensuring that the new capability supports all these cases in a reasonable way seemed non-trivial without accompanying end-to-end test cases. 

However, since the support is not activated, I am willing to merge this in for now and I definitely support your effort to add more tests. Once my current changes are gone in, hopefully developing such sharness tests becomes a bit easier.

**Comment by lipari** [comment]
> However, since the support is not activated, I am willing to merge this in for now and I definitely support your effort to add more tests. Once my current changes are gone in, hopefully developing such sharness tests becomes a bit easier. 

If you merge this whole, then I will withdraw the 1/2 [PR 104](https://github.com/flux-framework/flux-sched/pull/104) that I just created.

**Comment by dongahn** [comment]
@lipari: I still prefer this PR to be split into two. I will review the 1/2 PR 104 shortly.

**Comment by lipari** [comment]
Just pushed the second half of this PR which builds on PR 104.  The travis build will fail due to problems in flux-core reported in [Issue 505](https://github.com/flux-framework/flux-core/issues/505).

**Comment by dongahn** [comment]
@lipari: I am not sure if travis failed... The merge button is green. I've just submitted PR #106 which remove the use of heartbeat synchronization. Perhaps, you can review and merge that first and see if that allow you to work around the Travis issue in this PR?

**Comment by lipari** [comment]
Ok, I rebased to your merged changes and re-pushed this branch.  And the build succeeded.

**Comment by dongahn** [comment]
cool. thanks.

**Pull request merged**
