### PR TITLE
travis-ci: install libjansson-dev package

### LINKED ISSUE #209: flux-sched build broke
Not sure what changed in flux-core yet, but the build which followed the [latest sched merge](https://github.com/flux-framework/flux-sched/commit/665c88030cf59ca02972665f1385cbc3e429a4be) failed:
https://travis-ci.org/flux-framework/flux-sched/builds/166892546
configure: error: flux-core package not installed

### PR DESCRIPTION
**Pull request by garlick**
Since we build flux-core in travis, and flux-core
recently added a dependency on libjansson, ensure
that it is present in the travis build environment.

Fixes #209

### CODE REVIEW

**Comment by garlick** [comment]
Uh oh, is this a known issue?
```
ok 5 - resource file readable
/bin/bash: line 5: 40472 Segmentation fault      (core dumped) TESTRESRC_INPUT_FILE="/home/travis/build/flux-framework/flux-sched/flux-sched-0.2.0-56-gec14e60/_build/../conf/hype.lua" LUA_PATH="/home/travis/build/flux-framework/flux-sched/flux-sched-0.2.0-56-gec14e60/_build/../rdl/?.lua;/home/travis/local2/share/lua/5.1/?.lua;/usr/local/share/lua/5.1//?.lua;/usr/local/share/lua/5.1//?/init.lua;/home/travis/.luarocks/share/lua/5.1//?.lua;/home/travis/.luarocks/share/lua/5.1//?/init.lua;/usr/share/lua/5.1//?.lua;/usr/share/lua/5.1//?/init.lua;./?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/lib/lua/5.1/?.lua;/usr/local/lib/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;;" LUA_CPATH="/home/travis/build/flux-framework/flux-sched/flux-sched-0.2.0-56-gec14e60/_build/rdl/?.so;/home/travis/local2/lib64/lua/5.1/?.so;/usr/local/lib/lua/5.1//?.so;/home/travis/.luarocks/lib/lua/5.1//?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/lib/x86_64-linux-gnu/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;;" ${dir}$tst
FAIL: tresrc
```

**Comment by dongahn** [comment]
Do you have a stack trace from the core file? Looking at the segment right after `ok 5`, the tester does resrc/flow hierarchy generations and I know there has been some changes there. Do you see this on your system or travis?

**Comment by garlick** [comment]
That was a [travis failure](https://travis-ci.org/flux-framework/flux-sched/jobs/167094014).

**Comment by grondo** [comment]
We may want to also pull in gdb backtrace support for travis-ci from flux-core into flux-sched `.travis.yml`

**Comment by garlick** [comment]
I did get one core file in the TEST_INSTALL build
```
Found corefile for /home/travis/build/flux-framework/flux-sched/resrc/test/.libs/lt-tresrc
[New LWP 37121]
warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff8b7fe000
Core was generated by `/home/travis/build/flux-framework/flux-sched/resrc/test/.libs/lt-tresrc'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002b52dc63f031 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
Thread 1 (Thread 0x2b52db6c8080 (LWP 37121)):
#0  0x00002b52dc63f031 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00002b52dc63ec96 in strdup () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x0000000000409379 in xstrdup (s=<optimized out>) at xzmalloc.c:56
        cpy = <optimized out>
        __FUNCTION__ = "xstrdup"
#3  0x00000000004052a8 in resrc_new_from_json (o=0x2526730, parent=<optimized out>, physical=true) at resrc.c:699
        jpropo = 0x0
        property = <optimized out>
        jhierarchyo = <optimized out>
        jpropso = <optimized out>
        jtagso = 0x0
        basename = 0x1aad150 "socket"
        name = <optimized out>
        path = <optimized out>
        tmp = <optimized out>
        type = 0x19c6ec0 "socket"
        id = <optimized out>
        iter = {key = 0x1a401c0 "cpus", val = <optimized out>, entry = 0x2527310}
        resrc = 0x2527860
        parent_tree = <optimized out>
        size = <optimized out>
        uuid = "\242\267$\233\004>C\315\303f!\033\377\067\203", <incomplete sequence \326>
#4  0x000000000040557b in resrc_add_rdl_resource (parent=0x25225a0, r=0x25263b0) at resrc.c:731
        o = 0x2526730
        resrc = 0x0
        c = <optimized out>
#5  0x000000000040558b in resrc_add_rdl_resource (parent=<optimized out>, r=0x2521260) at resrc.c:734
        o = 0x2521590
        resrc = 0x25225a0
        c = 0x25263b0
#6  0x000000000040558b in resrc_add_rdl_resource (parent=<optimized out>, r=0x251a6f0) at resrc.c:734
        o = 0x251c5b0
        resrc = 0x251d5c0
        c = 0x2521260
#7  0x000000000040561b in resrc_generate_rdl_resources (path=<optimized out>, resource=0x40ab27 "default") at resrc.c:753
        resrc = 0x0
        rdl = 0x15acf20
        l = 0x159b500
        r = <optimized out>
#8  0x0000000000402677 in main (argc=<optimized out>, argv=<optimized out>) at tresrc.c:455
        filename = 0x7fff8b7edd39 "/home/travis/build/flux-framework/flux-sched/conf/hype.lua"
        topology = <optimized out>
        rc1 = 1
        rc2 = 1
        resrc = 0x0
        power_flow = 0x0
        bw_flow = 0x0
```

**Comment by grondo** [comment]
It is a little bit suspicious that this segv occurs after adding libjansson to the build, and the failure is in a function with json in the name. It probably isn't the issue since libjansson use is hidden behind libflux-core, but it might be something to look into?

**Comment by garlick** [comment]
Yes, I was thinking the same thing.

However did want to check with the sched guys:  Since  `jpropo` set to NULL in the trace, and the failure is triggered here:
```
property = xstrdup (json_object_get_string (jpropo));
```
is it correct for this code to assume that jpropo cannot be NULL?

**Comment by dongahn** [comment]
@lipari should chime in but it seems it is not safe to assume `jpropo` won't be NULL at first glance. A resource may have no properties. 

One thing I'm not clear is whether this condition will be taken care by. 

```
jpropso = Jobj_get (o, "properties");
```
Let me take a look.

**Comment by garlick** [comment]
When flux-core is installed off to the side so flux-sched can use it, the .la files are getting installed, and that may be causing some bleed-over of dependencies, e.g.
```
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libflux-core.la libflux-optparse.la '/home/travis/local2/lib'
```
and jansson is in there
```
# Libraries that this one depends upon.
dependency_libs=' /usr/lib/libmunge.la -ljansson -L/usr/local/lib /usr/local/lib/libczmq.la /usr/local/lib/libzmq.la -lsodium /usr/lib/x86_64-linux-gnu/libpgm.la -lgssapi_krb5 -lrt -lpthread -lutil -ldl -lm'
```
Hmm, maybe we should be stripping those out like we do when building the rpm?  I'll try that in a test commit.

**Comment by dongahn** [comment]
@grondo: assuming this construction method is to build a resrc object directly from a JSON object returned from RDL, what does the value object of the `properties` key look like? Any case where iterating through `json_object_object_foreachC` can result in a null or mal-formed string?

**Comment by grondo** [comment]
I think the properties "dictionary" should always exist but have no entries for resources without properties. You are talking about the json representation of an object though? I'd have to look at the code to remind myself how that is constructed. It certainly would be good programming practice to check for missing "properties" and treat as an empty set.

**Comment by dongahn** [comment]
> It certainly would be good programming practice to check for missing "properties" and treat as an empty set.

Agreed. I was just wondering about the initial condition. Also the value for each property is always a string? If so, something like the following should do. We'll probably have to revisit those JSON-based constructor and add safe guards as well. 

```
             json_object_object_foreachC (jpropso, iter) {
                 jpropo = Jget (iter.val);
                 if (jpropo) {
                     property = xstrdup (json_object_get_string (jpropo));
                     zhash_insert (resrc->properties, iter.key, property);
                     zhash_freefn (resrc->properties, iter.key, free);
                     Jput (jpropo);
                }
             }
```

**Comment by lipari** [comment]
This PR looks fine.  The json library changes revealed a logic flaw in resrc_new_from_json().  I'll have a fix for that in a forthcoming PR.

**Comment by garlick** [comment]
Oh sorry, I went to lunch but I was expecting to continue working on this.  To recap where we are
* missing libjansson package added
* hit core dump, suspected libjansson symbol leakage (somehow)
* noted .la files were being installed, removed them
* found first instance of missing build dependencies masked by the above
* still not building properly, not yet diagnosed

I'll open a bug.

**Pull request merged**
