### PR TITLE
reapi: Rename resource/hlapi to resource/reapi

### PR DESCRIPTION
**Pull request by tpatki**
Problem: In the current codebase, we mostly use the term reapi, except for the name of the directory hlapi under resource. This naming scheme should be consistent.

Rename resource/hlapi to resource/reapi and update relevant makefiles and headers.

### CODE REVIEW

**Review by jameshcorbett — APPROVED** [review]
Looks reasonable, for my sake though can you explain how the "re-" and "hl-" prefixes came about?

**Comment by tpatki** [comment]
@jameshcorbett I honestly don't know the legacy behind this naming scheme,  see this issue: https://github.com/flux-framework/flux-sched/issues/977

**Comment by jameshcorbett** [comment]
Oh right, I thought I had seen a discussion about it somewhere. Thanks for the pointer.

**Comment by trws** [comment]
Looks good to me, needs a rebase to merge cleanly so I'll do that, and set MWP.

**Comment by trws** [comment]
Thanks @tpatki!

**Pull request merged**
