### PR TITLE
Alternate Resource Model

### PR DESCRIPTION
**Pull request by lipari**
Add an alternate resource representation implemented in C that supports a variety of resource connectivity models.  Includes conversion of the sched framework and plugin API to the new model.

### CODE REVIEW

**Comment by garlick** [comment]
@lipari: the uses of `flux_event_send()` will need to be updated for the changes that just went in.  Here's one that can serve as an example for the others.
```
diff --git a/sched/schedsrv.c b/sched/schedsrv.c
index ce533d3..90e2050 100644
--- a/sched/schedsrv.c
+++ b/sched/schedsrv.c
@@ -103,15 +103,17 @@ static int
 signal_event ( )
 {
     int rc = 0;
+    zmsg_t *zmsg = NULL;
 
-    if (flux_event_send (h, NULL, "sched.event") < 0) {
-        flux_log (h, LOG_ERR,
-                 "flux_event_send: %s", strerror (errno));
+    if (!(zmsg = flux_event_encode ("sched.event", NULL))
+                                        || flux_event_send (h, &zmsg) < 0) {
+        flux_log (h, LOG_ERR, "%s: error sending event: %s",
+                  __FUNCTION__, strerror (errno));
         rc = -1;
         goto ret;
     }
-
 ret:
+    zmsg_destroy (&zmsg);
     return rc;
 }
 
```

**Comment by grondo** [comment]
It might also be helpful (if it is easy enough) to rebase this patch stack onto master to squash out all the existing merge commits that clutter the history.

**Comment by lipari** [comment]
I can squash the patch if you'd like, but I deliberately left the individual commits in as a way to understand its evolution.  If this is TMI, then I'll happily squash.

**Comment by garlick** [comment]
@lipari: subjective, but IMHO merge commits aren't interesting to have in the history later on when you want to understand a feature that went in.

**Comment by lipari** [comment]
Closing this pull request to be replaced by a squashed commit.

**Comment by grondo** [comment]
To clarify, I didn't mean squash all the commits into one big commit, but by doing a `git rebase` you may be able to clean up all the merge commits and have a nicer, linear history of your development, which may help others follow the evolution of the code more easily in the future. :smile:

**Pull request closed without merging**
