### PR TITLE
flux-sched: eliminate deprecated flux-core functions

### PR DESCRIPTION
**Pull request by lipari**
Addresses https://github.com/flux-framework/flux-sched/issues/112

### CODE REVIEW

**Comment by garlick** [comment]
Thumbs up from me.

**Comment by garlick** [comment]
May I press the button?   My PR is nearly ready, and it will break sched until this gets in.

**Comment by lipari** [comment]
@dongahn is at a conference.  I don't expect he would object to these changes.  Go ahead, please.

**Comment by dongahn** [comment]
This is fine in particular it will remove compilation warnings. But i just want to say using non JSON version of JSC will add some overheads due to redundant redundnat memory copying and converting between JSON-C to JSON string. 

I have [flux-core#208](https://github.com/flux-framework/flux-core/issues/208) and I will make it a priority to address that issue.

**Pull request merged**
