### PR TITLE
schedsrv: fix build_hwloc_rs2rank synchronization

### PR DESCRIPTION
**Pull request by garlick**
This allows sched to be loaded on the broker command line, without arguments (arguments are a bit of a problem for size > 1 as discussed in flux-framework/flux-core#584)

It replaces `kvs_get_string()` with `kvs_watch_once()` with initial value of NULL, so that the response from the KVS is delayed until the value is non-NULL, as may be the case if resource-hwloc has not completed its initialization on all ranks.

This also fixes a leak of the `kvs_get_string()` result on all but the last iteration.

### CODE REVIEW

**Comment by garlick** [comment]
oops, rebasing on current master.  Hmm, coveralls seems to be unhappy.

**Comment by dongahn** [comment]
This looks good. When does coveralls declare a "failure?" When the coverage ratio simply goes down?

**Comment by dongahn** [comment]
Maybe, you had a very small amount of increase in the exception branches... Does it really make sense to make coverall this sensitive? I wonder if they have some threshold control...

**Comment by grondo** [comment]
Oh, sorry my fault you have to manually set the coveralls acceptance. Don't
worry about it for now I will fix this evening.

**Comment by dongahn** [comment]
I see. :-) But the coverage check is COOL! I will merge @lipari's change first. And if/when @garlick rebase, i will merge this in.

**Comment by dongahn** [comment]
I just merged PR #127.

**Comment by garlick** [comment]
Just rebased on current master.

**Comment by dongahn** [comment]
Great. Thanks.

**Pull request merged**
