### PR TITLE
testsuite: update flux-sharness.sh and add fedora34

### PR DESCRIPTION
**Pull request by grondo**
This PR includes various updates and changes to the testsuite, including:

 - refresh to the latest flux-core `t/sharness.d/flux-sharness.sh` (keeping local changes)
 - set the `conf.shell_initrc` attribute to `/dev/null` for all `test_under_flux()` to address flux-framework/flux-coral2#16
 - add a fedora34 build to ci
 - (unrelated) add automake foreign mode and drop redundant files

The fedora34 build passes, but there are a lot of warnings of the form:

```
2022-02-01T18:47:46.4579430Z In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
2022-02-01T18:47:46.4579896Z                  from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
2022-02-01T18:47:46.4580261Z                  from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
2022-02-01T18:47:46.4580701Z                  from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
2022-02-01T18:47:46.4581050Z                  from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
2022-02-01T18:47:46.4581787Z                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
2022-02-01T18:47:46.4582224Z                  from /usr/include/boost/property_map/vector_property_map.hpp:14,
2022-02-01T18:47:46.4582579Z                  from /usr/include/boost/property_map/property_map.hpp:602,
2022-02-01T18:47:46.4583000Z                  from /usr/include/boost/graph/adjacency_list.hpp:27,
2022-02-01T18:47:46.4583317Z                  from ../resource/schema/resource_graph.hpp:15,
2022-02-01T18:47:46.4583619Z                  from ../resource/policies/base/dfu_match_cb.hpp:20,
2022-02-01T18:47:46.4584053Z                  from ../resource/policies/dfu_match_var_aware.hpp:18,
2022-02-01T18:47:46.4584352Z                  from policies/dfu_match_var_aware.cpp:11:
2022-02-01T18:47:46.4587458Z /usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
2022-02-01T18:47:46.4587999Z    13 | BOOST_HEADER_DEPRECATED("<iterator>")
2022-02-01T18:47:46.4588370Z       | ^~~~~~~~~~~~~~~~~~~~~~~
2022-02-01T18:47:49.8138656Z   CXX      policies/libresource_la-dfu_match_locality.lo
2022-02-01T18:47:49.8143616Z In file included from /usr/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
2022-02-01T18:47:49.8147892Z                  from /usr/include/boost/smart_ptr/detail/yield_k.hpp:23,
2022-02-01T18:47:49.8152153Z                  from /usr/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
2022-02-01T18:47:49.8156822Z                  from /usr/include/boost/smart_ptr/detail/spinlock.hpp:42,
2022-02-01T18:47:49.8161322Z                  from /usr/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
2022-02-01T18:47:49.8165569Z                  from /usr/include/boost/smart_ptr/shared_ptr.hpp:29,
2022-02-01T18:47:49.8169714Z                  from /usr/include/boost/property_map/vector_property_map.hpp:14,
2022-02-01T18:47:49.8173881Z                  from /usr/include/boost/property_map/property_map.hpp:602,
2022-02-01T18:47:49.8182420Z                  from /usr/include/boost/graph/adjacency_list.hpp:27,
2022-02-01T18:47:49.8182750Z                  from ../resource/schema/resource_graph.hpp:15,
2022-02-01T18:47:49.8183050Z                  from ../resource/policies/base/dfu_match_cb.hpp:20,
2022-02-01T18:47:49.8183371Z                  from ../resource/policies/dfu_match_locality.hpp:20,
2022-02-01T18:47:49.8183663Z                  from policies/dfu_match_locality.cpp:11:
2022-02-01T18:47:49.8184408Z /usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
2022-02-01T18:47:49.8185010Z    13 | BOOST_HEADER_DEPRECATED("<iterator>")
2022-02-01T18:47:49.8185238Z       | ^~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by jameshcorbett** [comment]
I saw two failures in my flux-coral2 environment. The old failure (``./t3301-system-latestart.t``) was fixed, though. Running the tests individually in verbose+debug didn't give me anything to work with

```
FAIL: t1017-rv1-bootstrap.t 15 - rv1-bootstrap: double nesting works
FAIL: t1018-rv1-bootstrap2.t 16 - rv1-bootstrap2: double nesting works
```

**Comment by grondo** [comment]
Thanks @jameshcorbett! These failures were reproducible or intermittent?

**Comment by jameshcorbett** [comment]
Reproducible.

**Comment by grondo** [comment]
Thanks, I'll look into it (though I don't quite understand the test at this point)

**Comment by jameshcorbett** [comment]
To reproduce, I build/install flux-core and flux-sched and flux-coral2, create a broker conf with this:

```
[job-manager]
plugins = [
   { load = "cray_pals_port_distributor.so", conf = { port-min = 11000, port-max = 12000 } }
]
```

and then export ``FLUX_CONF_DIR`` to the config file, start the installed flux, and run the tests.

**Comment by grondo** [comment]
Ok, it is obvious the problem is that for nested instances the configuration to disable the shell initrc is not preserved when running a subinstance. That approach therefore seemed flawed, and since we've got a workaround for flux-coral2, I've removed that part of this PR.

This PR now just updates `flux-sharness.sh` and adds a fedora34/GCC11 builder. I'll update the PR title.

**Comment by grondo** [comment]
I've added an additional commit here to fix an issue with the flux-sched testsuite discussed in flux-framework/flux-core#4126.

**Review by garlick — APPROVED** [review]
This LGTM!

No internal changes here so I feel fairly confident in in marking approved.

**Comment by dongahn** [comment]
LGTM. I am adding MWP.

>2022-02-01T18:47:46.4587458Z /usr/include/boost/detail/iterator.hpp:13:1: note: ‘#pragma message: This header is deprecated. Use <iterator> instead.’
> 2022-02-01T18:47:46.4587999Z    13 | BOOST_HEADER_DEPRECATED("<iterator>")

This seems an internal to Boost. I don't think we should do anything until Boost modernizes the code.

**Comment by grondo** [comment]
Mergify was modified, so someone will need to push the button this time.

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
