### PR TITLE
sched: Fix Issue 52

### PR DESCRIPTION
**Pull request by lipari**
Inserted a minimum requirement of one node into the resource request
logic.

### CODE REVIEW

**Comment by dongahn** [comment]
So this was a divided-by-zero problem then :-) The mod makes sense to me. But do we want to print out a warning message about "the resource shapes are not fully specified"?

**Comment by lipari** [comment]
In this case, I see it as a convenience to omit the full spec (nodes in this example).  While other omissions would require correction before being accepted, omitting a node count is excusable. This is consistent with our existing RM products.

**Comment by dongahn** [comment]
Ok. I propose to merge the fix unless others disagree.

**Comment by dongahn** [comment]
Based on the discussion going on in another discussion thread, my impression is there is no harm to merge this in while more changes may come in the future?

**Comment by lipari** [comment]
Agreed.  If nothing else, it eliminates the subject of this issue.  Any further improvements in various node/core scenarios will appear as the design evolves.

**Comment by dongahn** [comment]
Thanks.

**Pull request merged**
