### PR TITLE
simulator: Eliminate use of lwj.next-id

### PR DESCRIPTION
**Pull request by lipari**
Stop gap measure: ported new code from sched/schedsrv.c to
simulator/scheduler.c that leverages the job_status_cb to eliminate
watching for the lwj.next-id.  This allows us to merge PR 480 to the
flux-core.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks @lipari! 
As a verification, I'll try to test this PR against the branch for flux-framework/flux-core#480

**Comment by grondo** [comment]
Just to verify, `make check` was successful on this branch of `flux-sched` built against the branch for PR flux-framework/flux-core#480.

**Comment by lipari** [comment]
I'm verifying against PR 480 now.  My initial checks were against flux-core master.  Stay tuned...

**Comment by lipari** [comment]
Looks good!  flux-sched build and all tests passed when built against grondo:job-fu

**Comment by dongahn** [comment]
Thanks @lipari. I will merge this in as soon as PR480 gets in.

**Comment by grondo** [comment]
Since this PR works with both flux-core/master *and* PR 480, should this be
merged first?

**Comment by dongahn** [comment]
Sure.

**Pull request merged**
