### PR TITLE
Add missing CZMQ_FLAGS and FLUX_CORE_FLAGS

### LINKED ISSUE #187: zmq.h not found when installed in non-standard location
I have flux-core compiled and installed on a Ubuntu system in a non-standard location (i.e., `/opt/zeromq-4.1.4`).  `/opt/zeromq-4.1.4/lib/pkgconfig` was added to `PKG_CONFIG_PATH`, so that `pkg-config` correctly finds the package and generates the correct cflags and libs.  flux-sched's configure picks all of this up correctly, but I still get a compilation error in `common/libutil`:

```
# sherbein at sealand in ~/Repositories/flux-framework/flux-sched on git:dynam_sched ✖︎ [10:32:09]
→ make
make  all-recursive
make[1]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched'
Making all in src
make[2]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src'
Making all in common
make[3]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common'
Making all in libtap
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libtap'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libtap'
Making all in liblsd
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/liblsd'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/liblsd'
Making all in libutil
make[4]: Entering directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libutil'
  CC       log.lo
log.c:39:17: fatal error: zmq.h: No such file or directory
compilation terminated.
Makefile:427: recipe for target 'log.lo' failed
make[4]: *** [log.lo] Error 1
make[4]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common/libutil'
Makefile:395: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src/common'
Makefile:395: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched/src'
Makefile:462: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/data/hd1/Repositories/flux-framework/flux-sched'
Makefile:394: recipe for target 'all' failed
make: *** [all] Error 2
```

I was able to solve the problem by adding `$(CZMQ_CFLAGS)` to the `AM_CFLAGS` variable in `src/common/libutil/Makefile.am`.  Being unfamiliar with autotools, I am unsure if this is the correct solution.  If it is, I can submit a PR.

### PR DESCRIPTION
**Pull request by SteVwonder**
Fixes #187

### CODE REVIEW

**Comment by garlick** [comment]
Probably should be AM_CPPFLAGS not AM_CFLAGS in the libutil case.

**Comment by lipari** [comment]
> Probably should be AM_CPPFLAGS not AM_CFLAGS in the libutil case.

Assuming it works, what is the rationale for this?  IOW, why wouldn't you extend a CFLAGS def with another CFLAGSdef, and a CPPFLAGS def with another CPPFLAGS def?

**Comment by garlick** [comment]
See the automake manual I cited in #187.  Don't ask me to explain it :-)

You could be right, but when it comes to the voodoo that is autotools, a policy of RTFM isn't a bad way to go.

**Comment by SteVwonder** [comment]
Good catch @garlick. I totally forgot to do that. Will push a new version soon.

**Comment by garlick** [comment]
Looks good to me!

**Comment by lipari** [comment]
There is a conceptual distinction which would support extending CFLAGS with CFLAGS and CPPFLAGS with CPPFLAGS.  In a nutshell, CPPFLAGS include the –I and –D options while CFLAGS are the C compiler-specific flags.  Given that we’re compiling C code, there is no practical difference between which one is used.  So, unless there are any reservations, I will merge.

**Comment by garlick** [comment]
Merge away!

**Pull request merged**
