### PR TITLE
github: add workflow action to validate PR commits

### PR DESCRIPTION
**Pull request by grondo**
Copy workflow config from flux-core which validates that no commits in a PR are not valid for merging (i.e. have "fixup" or "squash" in the subject, or are merge commits)

### CODE REVIEW

**Comment by dongahn** [comment]
This looks good to me. @grondo: once you merge Issue #557, please rebase this. I will merge this in.

**Comment by grondo** [comment]
> This looks good to me. @grondo: once you merge Issue #557, please rebase this. I will merge this in.

Ok done.

**Comment by dongahn** [comment]
The failures appears to be due to a problem that PR #561 fixes. So PR #561 should be merged first before this.

**Comment by dongahn** [comment]
Pls rebase and this can go in.

**Comment by grondo** [comment]
Ok, rebased.

**Comment by dongahn** [comment]
LGTM. Merging.

**Pull request merged**
