### PR TITLE
Resrc deserialize

### PR DESCRIPTION
**Pull request by lipari**
As promised, the deserialization code.  The sched build fails however with the "jobs scheduled in correct order" problem.

### CODE REVIEW

**Comment by SteVwonder** [comment]
Given that the issue is with the tests/simulator not your code, I think we should just comment out the simulator tests from t/Makefile.  I suggested this in #63, but it didn't seem to be affecting Travis at the time, so we held off.  Something happened after the JSC merge, but I don't know what.  Since the simulator is going to change with my next PR, it probably isn't worth the effort to fix it right now (I will make sure they work with my changes).

**Comment by SteVwonder** [comment]
Also, thanks for getting this done so quickly.  This helps me a lot :)

**Comment by lipari** [comment]
Two things:  while the contents of the serialized resource data saved to the job record in the kvs was increased somewhat, there are more fields which could be included.  I held off doing so to minimize the noise, but if you find fields are necessary, they can easily be added to both the serialization and de-serialization operations.
The test that is failing is t1000-jsc.t.  I'm looking into that right now and when I have a fix, I'll add it to this branch/PR.

**Comment by lipari** [comment]
I have pushed an update to this PR with the fix and the job ordering tests commented out.  The build succeeded.

**Comment by dongahn** [comment]
@SteVwonder: if you come back online sooner than me, could you please review this in particular since we will be the initial user of this functionality?

**Comment by SteVwonder** [comment]
I looked over the code, and it looks good.  It seems to have everything I need for IO-Aware scheduling.

Just to give it a "test drive", I rebased my current work on top of @lipari's branch, and the serialization method seems to work just fine.  The updated format ends up in the KVS, etc.

Thanks again Don :smiley:

**Comment by dongahn** [comment]
@lipari: this looks great and should be merged ASAP. Sorry for the delay. Do you know why you got this Travis error? Could you rebase to see if the problem goes away?

**Comment by lipari** [comment]
I did actually rebase the branch.  Of the two travis builds of mine, the clang succeeded but the gcc hung when it went to execute this test:
ok 1 - jsc: expected job-event sequence for single-job scheduling.
I have yet to delve into the cause.  The test runs fine out of my home directory, so it is a mystery what changes under travis.

**Comment by lipari** [comment]
Issued a rebuild request and it passed!  Still need to discover the source of what I expect is a timing problem, but at least this should allow us to proceed with the next round of PR's.

**Comment by dongahn** [comment]
@lipari, we will see if we can find a reproducer for the jsc. But for now, I am merging this in.

**Pull request merged**
