### PR TITLE
Sched sim merge part 2

### PR DESCRIPTION
**Pull request by SteVwonder**
This fixes the tap tests that used the simulator (issue #63)
It also finishes off the simulator/schedsrv merge by adding EASY backfilling (issue #48)

### CODE REVIEW

**Comment by SteVwonder** [comment]
Ooooo. I didn't realize that my merge of Dong's PR would create an additional commit.  Should I rebase to fix this?  Or do we just leave that extraneous commit?

**Comment by grondo** [comment]
@SteVwonder: That is just a merge commit which records the merge from @dongahn into your branch. If it is empty (hard to tell from github interface, actuall), meaning there were no conflicts you had to fix up, then it is probably up to you whether to leave it in or rebase it away. 

it does serve the purpose of showing that you merged from @dongahn, but other than that just cosmetic history

**Comment by SteVwonder** [comment]
Thanks @grondo for the info.  I'm fine with leaving it then.
Out of curiosity though, what has been the standard practice over in flux-core for merge commits in PRs?

**Comment by grondo** [comment]
Standard practice has been to leave them in, especially those that you see from clicking the "Merge pull request" button on Github. Those merge commits do seem to serve useful historical purpose (even if they are a bit "noisy" when you are doing things like merging a single commit to fix an issue). 

We haven't had too many cases where there have been merges within a branch comprising a PR. It seems fine to me as long as there is not too much of that going on, and especially as long as the merge commit itself is "empty" (ie. there were no conflicts). You can avoid merge commits with conflicts by first doing a rebase on the branch being merged to the branch onto which you're merging.

(Hope that makes sense?)

**Comment by grondo** [comment]
One other note, I think if you merge from the command line from a branch that is rebased, git will do a "fast-forward" merge by default and you won't get a merge commit. (This might depend on the version of git you are using)

**Comment by SteVwonder** [comment]
@grondo, that makes sense.  Thanks!

**Comment by lipari** [comment]
I'm inclined to merge this.  I also have an idea on how to relegate backfill scheduling to a plugin instead of having it in with the sched framework.  I can work on that subsequent to this merge.  @dongahn, any objections?

**Comment by dongahn** [comment]
No objection, Don. Since we had a webex session and did code review, I’m ok since you are ok. And I’d love to hear your idea about how to refractor and expose schedule loop the plugins at some point. Thank you so much for your effort on this!

Dong
----------------------------------------------------------
Dong H. Ahn
925-422-1939
Development Environment  Group
Livermore Computing Division
Lawrence Livermore National Laboratory

**Pull request merged**
