### PR TITLE
flux-sharness: sync with flux-core

### PR DESCRIPTION
**Pull request by trws**
problem: I've been using heaptrack a lot, and other tools that need to be wrapped around flux itself.  This is difficult without something to integrate with test_funder_flux

solution: add some env vars to do a heaptrack recording or add a generic wrapper

### CODE REVIEW

**Review by grondo — COMMENTED** [review]
I like FLUX_TEST_WRAP, and this seems useful. Shall we add it to flux-core as well, since I think flux-sharness.sh is shared between projects.

**Comment by trws** [comment]
Yeah, I thought we'd do both or neither but kept needing it here so started that way.  Made a short attempt at updating our sharness.sh version as well, 1.2.1 is out and at least in sched we don't have the heredoc support and a few other things, but utterly failed I'm sorry to say.

**Comment by trws** [comment]
Now that this is merged in flux-core, just syncing up sched in this PR.

**Comment by trws** [comment]
Not sure what's up with codecov, the measure on their website is that this somehow increased coverage by 0.06%, and then on here it says it failed and decreased coverage by 0.2%... Everything else is passing, and this doesn't actually change any tests, or implementation so... Yeah, perplexed about that.

**Comment by grondo** [comment]
The PR shows indirect changes in `ephemeral.cpp` of -22%, with the whole of `ephemeral_t::insert()` being missed on this PR. 

I wonder if compiler version or flags differences could be exposing lines that did not appear before?

**Review by grondo — APPROVED** [review]
LGTM!

**Pull request merged**
