### PR TITLE
drop --with-flux-core-builddir and libforeign

### PR DESCRIPTION
**Pull request by garlick**
This PR eliminates `--with-flux-core-builddir` and libforeign by weaning flux-sched off of the barely-used libforeign/optparse, libforeign/jsonutil, and libforeign/base64; and by pulling in stripped down versions of libtap, liblsd (list only), libutil (shortjson, log, xzmalloc only).  It also copies in json-lua.[ch] from the lua bindings.

This approach was briefly discussed in #56 and pr #115.  The sources that are pulled in here are for the most part either trivial wrappers undergoing no development in flux-core, or originate from third parties and are designed for drop-in use.

### CODE REVIEW

**Comment by lipari** [comment]
Looks great, @garlick!  I see references to CODE_COVERAGE_CFLAGS in the three new common/lib* Makefile.am's.  Yet, unlike flux-core, there is no ax_code_coverage.m4 in place.  Is this something you plan to add to m4?

**Comment by grondo** [comment]
@lipari, I was thinking about adding that if it would be helpful. We could pull in some of the stuff we're doing in travis with flux-core, including `make distcheck` instead of just `make check`, a `make install` sanity check, as well as code coverage.

**Comment by lipari** [comment]
Sounds good.  Ready to merge if @dongahn agrees.

**Comment by garlick** [comment]
The coverage variables were cut and paste from flux-core; taking them out seemed like reverse progress so I just left them in but wasn't intending to make a committment to finish the job :-)

**Comment by garlick** [comment]
If you'd like this squashed down a bit I could do that...

**Comment by lipari** [comment]
only if you feel it is aesthetically more pleasing.  Otherwise, I'm ready to push the button as soon as @dongahn checks in.

**Comment by dongahn** [comment]
sorry folks. Let me take a look as well.

**Comment by grondo** [comment]
I thought that since this PR makes the issue with `subdir-objects` and out-of-tree sources and go away, we should add that option back to `AM_INIT_AUTOMAKE`. However, I gave it a whirl and we still get compilation failure under simulator:
```
make[1]: Leaving directory `/home/ubuntu/flux-sched.git/b/simulator'
~                                                                                               │Making all in test
~                                                                                               │make[1]: Entering directory `/home/ubuntu/flux-sched.git/b/simulator/test'
~                                                                                               │Makefile:612: ../../../simulator/.deps/tsched_lib-scheduler.Po: No such file or directory
~                                                                                               │make[1]: *** No rule to make target `../../../simulator/.deps/tsched_lib-scheduler.Po'.  Stop.
~                                                                                               │make[1]: Leaving directory `/home/ubuntu/flux-sched.git/b/simulator/test'
~                                                                                               │make: *** [all-recursive] Error 1
```

**Comment by grondo** [comment]
Oops, accidentally hit enter.

Apparently `subdir-objects` doesn't like building with sources from parent directories. The fix here would be to do what we've done in `flux-core` and build tests directly in parent directory and remove `tests/Makefile.am`

**Comment by grondo** [comment]
Ok, proposed fix (2 commits) at https://github.com/grondo/flux-sched/tree/subdir-objects

**Comment by lipari** [comment]
@grondo's mods look good to me.  Any preference for whether to subsume it into the present PR or submit is as a follow-on PR after this one is merged?

**Comment by grondo** [comment]
I'm going to have a follow on PR to update travis and add code-coverage anyway, so I could add it there.

**Comment by garlick** [comment]
oops I just pulled them in, but I can take them out if you like.

**Comment by garlick** [comment]
Woah, [this](https://travis-ci.org/flux-framework/flux-sched/jobs/111506965) is a pretty odd travis failure.

**Comment by garlick** [comment]
Oh man what did I screw up?

When I pulled in those two commits from grondo's subdir-objects branch, I did a fast-forward merge, which I thought was equivalent to cherry-picking them, but the travis failure above is 
```
$ git clone --depth=50 --branch=subdir-objects https://github.com/flux-framework/flux-sched.git flux-framework/flux-sched
Cloning into 'flux-framework/flux-sched'...
warning: Could not find remote branch subdir-objects to clone.
fatal: Remote branch subdir-objects not found in upstream origin
Unexpected end of command stream
```
Now why would it be trying to clone that branch?  This is what I did FYI
```
$ git fetch grondo
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 9 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From github.com:grondo/flux-sched
 * [new branch]      subdir-objects -> grondo/subdir-objects
$  git merge subdir-objects
Updating dcc5a35..c6c891a
Fast-forward
 configure.ac               |    3 +--
 simulator/Makefile.am      |   18 ++++++++++++++++--
 simulator/test/Makefile.am |   19 -------------------
 3 files changed, 17 insertions(+), 23 deletions(-)
 delete mode 100644 simulator/test/Makefile.am
$ git push origin foreign_invasion
Counting objects: 14, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 1.18 KiB, done.
Total 9 (delta 6), reused 0 (delta 0)
To git@github.com:garlick/flux-sched.git
   dcc5a35..c6c891a  foreign_invasion -> foreign_invasion
$ git log
commit c6c891ad933b5becb62bee38124a969dcdd58b82
Author: Mark Grondona <mark.grondona@gmail.com>
Date:   Wed Feb 24 15:31:50 2016 +0000

    build: add subdir-objects option to automake
    
    Add subdir-objects option to AM_INIT_AUTOMAKE

commit ee71d0fb5301bb40dbbbc18163558d4f5208fcdf
Author: Mark Grondona <mark.grondona@gmail.com>
Date:   Wed Feb 24 15:30:39 2016 +0000

    build: remove simulator/test/Makefile.am
    
    Move simulator tests Makefile.am rules into simulator/Makefile.am
    directly. Remove test/Makefile.am.

commit dcc5a35e6641416ec74d4980858e69e917917af2
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Tue Feb 23 14:16:38 2016 -0800

    sched: link against internal libs

[snip]
```

**Comment by garlick** [comment]
OK, just dropped those two commits and forced a push.

**Comment by grondo** [comment]
I wonder if I confused Travis. I accidentally pushed my subdir-objects branch to flux-framework/flux-sched, realized my mistake and deleted the branch immediately.

**Comment by grondo** [comment]
Looks good now, though.

**Comment by garlick** [comment]
I just noticed the README.md still references `--with-flux-core-builddir` so I'll push one more commit to address that shortly.

**Comment by grondo** [comment]
OK, I repushed a subdir-objects branch, let it pass, then deleted it. Let's see if that unbeffuddles travis.

**Comment by garlick** [comment]
We seem to be OK now - thanks!

So I think this PR is ready for consideration.

**Comment by lipari** [comment]
Close #56

**Pull request merged**
