### PR TITLE
NEWS.md: add release notes for v0.36.0

### PR DESCRIPTION
**Pull request by jameshcorbett**
Problem: there are no release notes for v0.36.0.

Add them.

Waiting on #1232 and #1236.

### CODE REVIEW

**Comment by trws** [comment]
Both merged, and this looks good to me.  It's in draft so I can't approve but LGTM.

**Comment by jameshcorbett** [comment]
Force-pushed to change the date to today, will set MWP.

**Comment by jameshcorbett** [comment]
Oh, maybe I need an actual approval for MWP to go to work. @grondo or @trws ?

**Review by trws — APPROVED** [review]

**Comment by trws** [comment]
Done

**Pull request merged**
