### PR TITLE
Address warnings

### PR DESCRIPTION
**Pull request by lipari**
This addresses a number of compile-time warnings that improve code reliability.  It also fixes the Makefile.inc to track the new flux-core library names.

### CODE REVIEW

**Comment by grondo** [comment]
Do we need to fix flux-core's `travis-dep-builder.sh` to add --no-check-certificate for openmpi.org?

**Comment by lipari** [comment]
[PR 533](https://github.com/flux-framework/flux-core/pull/533) does this.

**Comment by grondo** [comment]
Thanks I didn't see that one yet.

**Comment by lipari** [comment]
Trouble in River City.  Something zigged in flux-core that broke flux-sched.  I can investigate this afternoon.

**Comment by grondo** [comment]
Yeah I opened flux-framework/flux-core#534 on this one

**Comment by lipari** [comment]
Thanks, @grondo.  Simply increasing the clone depth was all that was needed.  Build succeeded!

**Comment by dongahn** [comment]
Looks good otherwise. @lipari: let me know if you want to tackle that xasprintf as part of this. If not, I can merge this in as is.

**Comment by lipari** [comment]
working on it now...

**Pull request merged**
