### PR TITLE
NEWS.md: add release notes for v0.38.0

### PR DESCRIPTION
**Pull request by jameshcorbett**
Problem: there are no release notes for v0.38.0.

Add them.

### CODE REVIEW

**Comment by grondo** [comment]
@trws , anything pending that should make it into this release?

**Review by grondo — APPROVED** [review]
LGTM if @trws agrees. Thanks!

**Comment by trws** [comment]
This is a decent place to break IMO, I'd recommend explicitly noting the new compiler requirements and the fact that we dropped support for the default focal compiler in this release in the notes though.

**Comment by jameshcorbett** [comment]
Done for the compiler versions. I think the focal drop was from last release? In `0.37.0` we have

```
### Build/Testsuite
 * actions/docker: add ~el9~,f40,noble drop focal (#1257)
```

Setting MWP.

**Comment by trws** [comment]
I think that's right, thanks!

**Pull request merged**
