### PR TITLE
codecov: ignore vendored json.hpp

### PR DESCRIPTION
**Pull request by SteVwonder**

### CODE REVIEW

**Comment by dongahn** [comment]
Hmmm... It is still 68.04%...

**Comment by SteVwonder** [comment]
It looks like codecov changed the yaml format out from underneath us.  So it has just been reverting to the default configuration and not respecting our ignored paths.  I wonder if that happened recently and is part of the reason why our coverage fell.

Either way, I sync'd up with what is being used over in flux-core.  Side benefit that the codecov bot will now delete any old comments before posting new ones.  So our PR discussions should look much cleaner going forward.

**Comment by SteVwonder** [comment]
That seems to have brought it back up to 77.5%

**Comment by dongahn** [comment]
72.2%?

**Comment by dongahn** [comment]
Actually 73.5%. Much better than before...

**Comment by SteVwonder** [comment]
Oh yeah. Sorry. I was looking at the wrong percentage.

Good to merge?

**Comment by dongahn** [comment]
Yup. Adding MWP.

**Review by dongahn — APPROVED** [review]

**Pull request merged**
