### PR TITLE
sched: Print error messages when schedule_job cannot run

### LINKED ISSUE #347: Need more useful error messages when schedule_job fails
@koning hit this when he used `job.submit` rpc with slightly incorrect keys. The `schedule_job ()` was getting a NULL resrc_reqst object and so it returned, but it didn't print out any error message about this failure.

### PR DESCRIPTION
**Pull request by dongahn**
Resolve #347.

### CODE REVIEW

**Comment by dongahn** [comment]
Just rebased to the master.

@SteVwonder: if this can be merged quick, this may make my life a bit easier to create a PR for #352. Thanks.

**Comment by SteVwonder** [comment]
LGTM! I am about to head to bed for my early flight tomorrow. I don’t want to merge until Travis comes back green. Feel free to merge yourself tonight if you want. Otherwise, I’ll push the button tomorrow morning.

**Comment by dongahn** [comment]
This can definitely wait. Have a safe travel!

**Comment by dongahn** [comment]
Thanks.

**Pull request merged**
