### PR TITLE
A Fix and an Update

### PR DESCRIPTION
**Pull request by lipari**
Fix a compile error with a call to kvs_get_dir() and grab the latest shortjson.h from flux-core

### CODE REVIEW

**Comment by dongahn** [comment]
Thanks @lipari.  I will assume the first commit fixes  the Travis failures seen with #198. This is not your code but I thought I might ask a question to @garlick about the need for updating the job's kvs_dir handle.It seems awkward a directory  handle needs to be destroyed and reread after a commit... (There is a TODO note anyway)

**Comment by garlick** [comment]
The `kvsdir_t` contains a list of keys (at the level of the directory) that will become out of date if keys are added/removed at that level.  However, a `kvsdir_t` does not behave like a snapshot with respect to keys at other levels unless it was created by the new `kvs_get_dirat()`.  I know, I know, this API is awful.

So refresh if you need to update the list of keys at that level.

And you should check the return value of all kvs calls for error too.

**Comment by lipari** [comment]
> And you should check the return value of all kvs calls for error too.

Created [Issue 202](https://github.com/flux-framework/flux-sched/issues/202) to capture that advice.

**Comment by lipari** [comment]
@dongahn or @SteVwonder, I believe this is ready for merging.  I've created a separate issue to decouple the return check of the kvs calls to a follow-on effort.

**Comment by lipari** [comment]
@dongahn or @SteVwonder, I merged @grondo's fix instead.  I"ll push a new PR with just the shortsjson update

**Comment by grondo** [comment]
Sorry Don! I somehow missed this PR :-(

**Comment by lipari** [comment]
Np at all

**Pull request closed without merging**
