### PR TITLE
build: do not install libflux-rdl.so, fix rebuild of aclocal.m4 on first make

### PR DESCRIPTION
**Pull request by grondo**
This PR turns `libflux-rdl.so` into a convenience library instead of an installed library as discussed in #420. It was simpler to keep the other requisite convenience libs (libutil, liblsd) as part of `libflux-rdl.la` and remove them when duplicated in `LIBADD`, than to leave them out of `libflux-rdl.la` and then add them by hand everywhere `libflux-rdl.la` is used. However, I do have a working implementation of the other way if that is preferred.

I also got annoyed and fixed the issue where `make` thought it had to rebuild `$(srcdir)/aclocal.m4` after every `autogen.sh && ./configure` (this was because `autogen.sh` was moving it to where it couldn't be found)

### CODE REVIEW

**Comment by dongahn** [comment]
> This could be because the AUX_DIR and CONFIG_DIR are different in flux-sched (m4 and config
respectively).

Odd... Do you know why sched ends up using both `AUX_DIR` and `CONFIG_DIR`? It seems keeping all m4 scripts in `config` might make thing more readable and consistent with `flux-core.`

**Comment by dongahn** [comment]
@grondo: LGTM! Thanks.

**Comment by dongahn** [comment]
If that is not that time consuming, I think it makes sense just fixing it as part of this PR. Thanks.

**Comment by grondo** [comment]
Ok, I've pushed a commit that moves the contents of `m4` into `config` to more closely match existing practice in `flux-core`

**Comment by dongahn** [comment]
@grondo: Great! I will take a look at the PR after my meeting at 10AM and merge if no other changes are required. Thanks.

**Comment by dongahn** [comment]
@grondo: m4 --> config looks great to me. One thing though, with this move, do we want to revert the https://github.com/flux-framework/flux-sched/pull/421/commits/084b433b4fdb9bee9fcccdbc163d724b58fbdb82 change so that `flux-sched`'s `augogen.sh` becomes more consistent with `flux-core`?

**Comment by dongahn** [comment]
Thanks.

**Comment by dongahn** [comment]
Thanks @grondo. Yes, `AM_MAINTAINER_MODE([enable])` is really a good addition. I vaguely remember I had to add this to avoid some timestamp mishap.

**Comment by dongahn** [comment]
@grondo: Hmmm, for some reason I'm still seeing your `autogen.sh` change in 860b063...

**Comment by grondo** [comment]
> @grondo: Hmmm, for some reason I'm still seeing your autogen.sh change in 860b063...

You mean that commit is still in this branch? I did force push, so you might have an old copy.

If you mean that the move of `aclocal.m4` is still removed from `autogen.sh`, then that is intentional because it was the root cause of the problem where `make` would rerun `configure` the first time after `autogen.sh` (`aclocal.m4` needs to be at the top level)

This will make `autogen.sh` from flux-core and flux-sched match after flux-framework/flux-core#1912 is merged.

**Comment by dongahn** [comment]
> If you mean that the move of aclocal.m4 is still removed from autogen.sh, then that is intentional because it was the root cause of the problem where make would rerun configure the first time after autogen.sh (aclocal.m4 needs to be at the top level)

Ah I see. I somehow mistakenly thought that `aclocal.m4` being moved to `config` directory is okay when you don't have both `AUX_DIR` and `CONFIG_DIR`, not leading to a redundant configure rerun . I will merge as is then.

**Comment by grondo** [comment]
>  I somehow mistakenly thought that aclocal.m4 being moved to config directory is okay when you don't have both AUX_DIR and CONFIG_DIR, not leading to a redundant configure rerun 

I thought that at first as well. However, if you look at `aclocal.m4` location in generated Makefiles, you find it should be in top_srcdir:

```
grondo@peep:~/git/flux-sched$ grep aclocal\\.m4 Makefile
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
```

I'm not sure why `-I config` doesn't change that, but I didn't want to fight it too much. It was easier to just leave `aclocal.m4` where `./autoreconf` thought it should go...

**Comment by dongahn** [comment]
Agreed.

**Pull request merged**
