### PR TITLE
sched: replace direct read of kvs with rpc to resource-hwloc

### PR DESCRIPTION
**Pull request by lipari**
Leverages resource-hwloc's topo rpc instead of reading the kvs
directly.

### CODE REVIEW

**Comment by garlick** [comment]
Apologies if this has already been discussed but why not read this from the KVS?

Does the single RPC directed to FLUX_NODEID_ANY achieve what the old code did by iterating through the ranks pulling in XML from each one?

**Comment by dongahn** [comment]
My guess is resrc_generate_xml_resources has the walking logic to populate resrc_t objects. 

Actually, I have been looking at the latest addition to schedsrv.c and found that the code base is getting increasingly complex with various support like multiple reader options and emulation mode. 

I have been trying to factor out things and one of the abstraction is resource reader class called rsreader. 

I have to believe that the new bulk loading can be the basis for a placeholder method in it called rsreader_hwloc_bulkload.

@lipari, I plan to post a prelim PR today and if you don't mind, can you please look at the new code base before we proceed with this change?

**Comment by lipari** [comment]
Utilizing the resource-hwloc's topo rpc is similar to using the jsc to report job status.  It allows the owner, in this case the resource-hwloc, to own and deliver info that it stores in the kvs.

I will eventually need to target each resource-hwloc specifically and get it to return the resources it sees.  But for now they all report the same inventory of all the resources across the instance.

**Comment by lipari** [comment]
> @lipari, I plan to post a prelim PR today and if you don't mind, can you please look at the new code base before we proceed with this change? 

Sure.

**Comment by garlick** [comment]
Since `resource-hwloc` already does the work to store data instance wide hwloc data in the KVS, it would be less scalable to `flux_rpc_multi()` than to read the data directly from the KVS.

There's no reason modules can't have "contracts" using the KVS as intermediary.

**Comment by lipari** [comment]
Good point.  I will withdraw the PR.

**Pull request closed without merging**
