### PR TITLE
Issue153: Better resource unmatch test and etc

### PR DESCRIPTION
**Pull request by dongahn**
Fix Issue #153. 

- Remove rdl-config=RDL-file option from the tests that are not designed to test a RDL-hwloc inconsistency
- Improve the verbosity for RDL != hwloc condition
- Add fail-on-error option to the sched module for better testing

### CODE REVIEW

**Comment by grondo** [comment]
@dongahn, nice work!

One question:  You mention that sched "sets name to hostname" in hwloc reader mode. RDL itself is not supposed to be node-centric and therefore in Lua-based rdl config code `rdl_resource_name()` does not differentiate between "node" types vs other types, and will return `name+id` for *any* resource that has an ID field. (e.g. `{ name: "core", id: 1 }` returns `rdl_resource_name() == "core1"`)

I just wanted to make sure this doesn't further affect sched if it is currently behaving node-centric.

**Comment by dongahn** [comment]
@grondo: Thank you for the quick response and good question!

@lipari should chime in for this question. If I read hwloc reader code correctly in [here](https://github.com/flux-framework/flux-sched/blob/master/resrc/resrc.c#L679), the name of resrc is actually set to name+id where id is the logical index of hwloc_object_t type except for the node type. For node, resrc sets it to hostname -- and we had some issues when it didn't do it that way: PR #109.  

I think it will be good if we go through resrc to make sure it builds its internal fields consistently across different reader modes: rdl and hwloc. To me, it is okay as far as the name always returns the same information regardless of the reader mode. You may have a different opinion though.

**Comment by lipari** [comment]
@grondo, the resrc code mirrors the conventions established with [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc) as well as the rdl code itself.  When generating a resrc_t object from an RDL file, I opted to use the rdl_resource_json() instead of the rdl_resource_name() call.  I'd have to check, but if the "name" field is getting an id appended, that is where it comes from.

**Comment by dongahn** [comment]
FYI -- I've created Issue #157. To discuss general (in)consistency issues on the semantics of resrc fields between different reader modes, I'd suggest we take it to #157.

Let's keep this PR to discuss specifics relevant to this particular resource match test failure patch.

**Comment by dongahn** [comment]
Please don't merge. I will adapt this PR after @lipari's PR from Issue #157 is merged.

**Comment by lipari** [comment]
[PR 161](https://github.com/flux-framework/flux-sched/pull/161) submitted.

**Comment by dongahn** [comment]
OK. Rebased to the latest master and forced a push.

As agreed, with PR #161, I took off the hostname support from this PR. The rest of the changes seem work out of box on the latest HEAD of master.

**Comment by lipari** [comment]
@dongahn, looks good!  Only two suggestions:
* RDL_CONF_DEFAULT in t/sharness.d/sched-sharness.sh is vestigial.  Is there a need/plan to use it somewhere/sometime?
* In isolation, the name of the `--fail-immediate` option seems confusing.  Is it an option to make the sched plugin fail at launch?  How about naming the option `--rdl-conf-reqrd` or `--rdl-conf-only`?

**Comment by dongahn** [comment]
Thanks!

> RDL_CONF_DEFAULT in t/sharness.d/sched-sharness.sh is vestigial. Is there a need/plan to use it somewhere/sometime?

I believe this needs to be removed. I will change and do a push. 

> In isolation, the name of the --fail-immediate option seems confusing. Is it an option to make the sched plugin fail at launch? How about naming the option --rdl-conf-reqrd or --rdl-conf-only?

The intent of this option is to fail the `sched` on any soft error for testing purposes beyond this rdl unmatch error. Without such an option, it becomes difficult to add a test case like the new "unmatch failure test" into shardness. I am open to other naming suggestions but the both of your suggestions seems too rdl centric...

**Comment by lipari** [comment]
I see.  How about `--fail-on-error` then?

**Comment by dongahn** [comment]
I like `--fail-on-error` better!

**Comment by dongahn** [comment]
OK. Forced a push.

**Pull request merged**
