### PR TITLE
Condense the core id list in R_lite

### PR DESCRIPTION
**Pull request by dongahn**
This is somewhat experimental. I at least wanted to do this to see the valgrind results on Travis. So don't merge yet.

Pull in nodeset class and friends from `flux-core` and add those files to flux-ached's libutil.

Incorporate nodeset to`R_lite` generator in `resrc_tree.c` to condense the list.

### CODE REVIEW

**Comment by dongahn** [comment]
That be awesome for various purposes! Could the name also change to something more generic, if that's the case?

**Comment by garlick** [comment]
Sure, I guess - were you thinking of packaging in a separate library similar to libflux-optparse.so?

Suggestions on a new name?  It's implementation is based on the [vEB trie](https://en.wikipedia.org/wiki/Van_Emde_Boas_tree).

Maybe it would be worth making a cleanup pass through the API and creating a man(3) page also.

**Comment by garlick** [comment]
> Suggestions on a new name?

rankset?

**Comment by grondo** [comment]
I'm fine with `flux_nodeset_t`, but if the name must be changed, I would suggest `idset` or `intset` since it can represent any set of integers or identifiers. (e.g. here it is being used for core ids.

**Comment by dongahn** [comment]
I like `idset`

**Comment by dongahn** [comment]
Will rework this against the new `flux_dset` API.

**Pull request closed without merging**
