### PR TITLE
Makefile.am:  Added $(AM_*FLAGS) to definitions where missing

### PR DESCRIPTION
**Pull request by lipari**
and fixed the warnings that showed up in resrc.c and resrc_tree.c

### CODE REVIEW

**Comment by dongahn** [comment]
@lipari: This looks good. Could you split the commit into two? One with Makefile.am changes and the other with resrc warning fixes?

**Comment by lipari** [comment]
> @lipari: This looks good. Could you split the commit into two? One with Makefile.am changes and the other with resrc warning fixes?

Done.

**Comment by dongahn** [comment]
Nice work! Dead code elimination increased the testing coverage too :-) I will merge it as soon as Travis turns green.

**Comment by dongahn** [comment]
Hmmm some Travis checks failed.

**Comment by dongahn** [comment]
I don't understand why those two configs failed on `gcc-4.9 g++-4.9`

**Comment by dongahn** [comment]
Ok. I kicked it again and all green. It probably was a transient error.

**Pull request merged**
