### PR TITLE
Tidy up JGF match writer support

### PR DESCRIPTION
**Pull request by dongahn**
This PR cleans up match writer support in preparation for the upcoming JGF reader support. It contains:

- Drop support for pretty printing for JSON-based writers
- Adjust the schema and internals of JGF format to support general cases and the future JGF reader
- Two bug fixes

### CODE REVIEW

**Comment by dongahn** [comment]
@SteVwonder, @tpatki and @milroy: this PR is ready to be reviewed. This should be merged before PR #521, which actually has the JGF reader support.

**Comment by dongahn** [comment]
PR #523 has been merged. This needs to be rebased to the upstream master.

**Comment by dongahn** [comment]
Rebased to the current master.

**Comment by dongahn** [comment]
Great! Thanks you @milroy. I will go ahead and change the spacing issues since I will have to rebase this anyway. Once that's done, I would say we merge this so that @tpatki and/or @SteVwonder can focus on PR #521, which would be more involved.

**Comment by dongahn** [comment]
@milroy" OK. I fixed those style issues and rebase this to the master. Once Travis CI turns green, this can go in. Feel free to push the merge button if you want.

**Comment by milroy** [comment]
@dongahn and I discussed this PR, and since it's relatively small I merged it on behalf of the other reviewers.

**Comment by dongahn** [comment]
Thanks @milroy!

**Comment by SteVwonder** [comment]
Thanks @milroy and @dongahn!

**Pull request merged**
