### PR TITLE
resource: improve error messages for jobspec parse errors

### LINKED ISSUE #1002: error handling for unsatisfiable constraint could use improvement
This command (a malformed constraint) gets an "internal" error which may not be the greatest choice.
```
$ flux mini run --requires rank:z hostname
flux-mini: ERROR: [Errno 22] Internal match error
```
Also it logs this at LOG_ERR, but errors that a user can cause with bad input (and that they are informed of) are not really appropriate to log like this.
```
2023-02-06T01:26:50.505676Z sched-fluxion-resource.err[0]: satisfiability_request_cb: Internal match error: Invalid argument
```

Same error specifying a host that is excluded/unknown
```
$ flux mini run --requires host:picl0 hostname
flux-mini: ERROR: [Errno 2] Internal match error
```
and logs
```
2023-02-06T01:30:41.126749Z sched-fluxion-resource.err[0]: satisfiability_request_cb: Internal match error: No such file or directory
```
although sometimes I get an "Unsatisfiable request" error.  I'm not sure what the difference is between these two requests:
```
$ flux mini run --requires host:picl6 hostname
flux-mini: ERROR: [Errno 2] Internal match error
$ flux mini run --requires host:picl7 hostname
flux-mini: ERROR: [Errno 19] Unsatisfiable request
```
They both are requesting hosts that are valid but not in the requested queue.  (Nothing is logged in the latter case). 
```
$ flux resource list
     STATE QUEUE      PROPERTIES NNODES   NCORES    NGPUS NODELIST
      free debug,all                  1        4        0 picl1
      free debug,all  4g              1        4        0 picl2
      free batch,all                  3       12        0 picl[3-4,6]
      free batch,all  4g              1        4        0 picl5
      free batch,all  testprope+      1        4        0 picl7
 allocated                            0        0        0 
      down                            0        0        0 
```

### PR DESCRIPTION
**Pull request by grondo**
This possibly could have been accomplished by changing how exceptions are propagated and handled in the resource module, but I wasn't sure how to do that, so here we use a `flux_error_t` to propagate the exception error string back to where it can be returned in an error response to the feasibility RPC.

Fixes #1002

### CODE REVIEW

**Comment by garlick** [comment]
Better!
```
$ flux mini run --requires host:picl1 hostname
picl1
$ flux mini run --requires host:picl2 hostname
picl2

# should this be unsatisfiable?
$ flux mini run --requires "host:picl1 rank:2" hostname
flux-mini: ERROR: [Errno 2] Internal match error: 

# bravo!
$ flux mini run --requires rank:z hostname
flux-mini: ERROR: [Errno 22] Internal match error: Invalid idset `z'
$ flux mini run --requires "host:picl[1" hostname
flux-mini: ERROR: [Errno 22] Internal match error: Invalid hostlist `picl[1'

$ flux mini run --requires rank:7 hostname
flux-mini: ERROR: [Errno 19] Unsatisfiable request
$ flux mini run --requires rank:6 hostname
flux-mini: ERROR: [Errno 19] Unsatisfiable request

# should this be unsatisfiable?
$ flux mini run --requires host:xyz hostname
flux-mini: ERROR: [Errno 2] Internal match error: 
```

Also in the first commit title s/fro/for/

**Comment by grondo** [comment]
Good catch on those other errors. I'll have to study the code more to see what is causing the difference between "match error" and "unsatisfiable request"

**Review by garlick — APPROVED** [review]
LGTM

**Comment by grondo** [comment]
Ok, maybe good to merge this half measure as-is and get the other error message bugs noted in new issues.
Setting MWP

**Pull request merged**
