### PR TITLE
add infrastructure for sphinx documentation

### LINKED ISSUE #772: docs: add sphinx support
We have a few markdown Readmes that could get slurped up and put into a RTD site.  And it will be good to have Sphinx in place for when manpages (#160) start getting created.

### PR DESCRIPTION
**Pull request by grondo**
This PR adds the build infrastructure for generating manpages and html from reStructuredText via sphinx.

The Makefiles, `conf.py`, test directory, etc are copied from other flux-framework projects.

As a demo, a stub `flux-config-sched-fluxion-qmanager(5)` man page is added. It is in a separate commit so the steps to add a manpage are evident.

Fixes #772

### CODE REVIEW

**Comment by grondo** [comment]
I added a missing `.readthedocs.yaml` file and pushed. I also configured the readthedocs site for flux-sched, so we should see the build rendered as one of the CI checks now [here](https://flux-sched--906.org.readthedocs.build/en/906/)

**Comment by grondo** [comment]
I keep seeing a hang in `t1011-dynstate-change.t` at the end of the test here:

```
expecting success: 
      cleanup_active_jobs
  
  flux-queue: Scheduling is disabled
  flux-job: Canceled 6 jobs (0 errors)
```

I think we may also be seeing this in flux-core's flux-sched CI test, so I'll open an issue.

**Review by garlick — APPROVED** [review]
LGTM!

**Comment by grondo** [comment]
I wonder if I should try to fill in the `TBD` in the `DESCRIPTION` section of `flux-config-sched-fluxion-qmanager(5)` before setting MWP?

**Comment by grondo** [comment]
I found an error in the sphinx `conf.py` and also replaced `TBD` with a very generic but presumably accurate statement. The `flux-config-sched-fluxion-qmanager(5)` manpage still only serves as a placeholder and needs to be augmented, but perhaps this is a good enough starting point to merge.

**Comment by garlick** [comment]
Looks good!

**Comment by grondo** [comment]
Thanks! Setting MWP.

**Pull request merged**
