### PR TITLE
add resource update support

### PR DESCRIPTION
**Pull request by dongahn**
This PR is WIP because I will need to clean up #537 first. It adds support for update as described in Issue #528. 

- Add update() to the base reader class as well as its derived classes.

- Implement update() within the JGF reader class. Other derived classes get an empty update() implementation for future extension.

- Integrate the update method of readers into the traverser code and Overload run() method so that the traverser can run to update the resource graph using a JGF subgraph, jobid, starttime and duration as well as a reader object.

- Integrate update command into resource-query. The overall syntax:
  `resource-query> update allocate jgf_file jobid starttime duration`

- Add two shares tests: one dealing with a machine with a single subsystem and the other containing two subsystems.

### CODE REVIEW

**Comment by dongahn** [comment]
FYI -- Travis CI was failing because there is a git filter for the files that end with `.out` so a couple of expected output files didn't go in. I just forced to add them back.

```console
[gingerfoot:data/resource/expected] ahn1% git add -f update_multi/
```

Once CI is happy, this PR should be okay to be reviewed and I requested @milroy and @SteVwonder as the reviewers. 

However, what would be better for everyone is to work and land PR #527 first and rebase this PR on top of that. So that will be my next task.

**Comment by dongahn** [comment]
I rebased this to PR #537 which has two intermediate commits that I just added to address @milroy's review. 

As PR #537 is getting closer to be merged, I also dropped "WIP" from the title of this PR: This PR should be ready to be reviewed as well although this will needs to be adjusted once PR #537 is merged.

@SteVwonder and @milroy: if you want to review this PR,  you can do that from 
the 7d10b0c commit.

**Comment by dongahn** [comment]
@milroy and @SteVwonder: I rebased this w/ PR #537 and the Travis CI is green. There is a slight decrease in the testing coverage. I glanced through the diffs and they seem to be reasonable. 

This should be good for your reviews.

I wonder if there is a way to decrease the sensitivity for PASS/FAILURE criteria. @grondo: do you know how?

**Comment by dongahn** [comment]
> However, the first 14 commits have already been merged in PR #537, so this PR is a bit confusing. I'm not sure what complexity that creates for merging.

Sorry about this. This should have been rebased and conflict should have been resolved. This probably fell through the crack through travel and such. I will address your comments and as part I'd that rebase this to the current master.

**Comment by dongahn** [comment]
@milroy: I pushed two new commits (which should be squashed later) for your review. I will also rebase this to the master to see if the previous commits will all disappear.

**Comment by dongahn** [comment]
@milroy: OK. With the new rebase, all of the previous commits disappeared with no conflicts! Once you take a brief look at the last two commits which then gets squashed, this PR can go in. I am okay if this goes in before our new tag. I will just add a few more items to NEWS.

**Comment by milroy** [comment]
The new commits look good.  I'm merging this PR.

**Comment by dongahn** [comment]
Oops. I needed to squash the last two commits though...

**Comment by dongahn** [comment]
For future reference, I use a commit message with "[squash]:... " to indicate that commit needs to be squashed once the review is done... 

@grondo or @garlick: is okay to rewrite the commit history of master? Maybe this is minor enough we just leave this as is.

**Comment by garlick** [comment]
Your call, but I'd probably just leave it.

**Comment by grondo** [comment]
If it is soon enough to where travis builds haven't even finished, then it may be ok to rewrite history of master in extreme cases. (force-stop all travis builds first). 

I wonder if we could make it so that branches with commits having these types of tags can't be merged. Something to look into.

**Comment by dongahn** [comment]
Ok. I will just leave it. Not much harm done, other than having some intermediate commits


> I wonder if we could make it so that branches with commits having these types of tags can't be merged. Something to look into.

This is a common enough workflow so having a way to enforce this (not merge yet) makes sense to me.

**Comment by milroy** [comment]
Sorry about the premature merge @dongahn.  I misunderstood your comment about squashing the last two commits.  I'll be careful not to do that in the future.

**Comment by dongahn** [comment]
Not a big deal. Thank you for the review -- much harder part!

**Pull request merged**
