### PR TITLE
Support cmake 3.18

### LINKED ISSUE #1066: build: configure errors on debian 11 system after cmake changes
Problem: flux-sched `configure` fails on debian system with flux-core installed as a system package

flux-sched built here before, so the normal dependencies should be correct.   I installed the system cmake package which is 3.18.4.
```
 garlick@picl0:~/proj/flux-sched$ ./configure
-- VER 0.28.0-60-gcc781dd3
-- The CXX compiler identification is GNU 10.2.1
-- The C compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Building flux-sched version 0.28.0-60-gcc781dd3
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- flux found in PATH and no specific FLUX_CORE_PREFIX specified, using /usr
-- Checking for module 'flux-core'
--   Found flux-core, version 0.54.0
-- Checking for module 'flux-hostlist'
--   Found flux-hostlist, version 0.54.0
-- Checking for module 'flux-idset'
--   Found flux-idset, version 0.54.0
-- Checking for module 'flux-optparse'
--   Found flux-optparse, version 0.54.0
-- Checking for module 'flux-pmi'
--   Found flux-pmi, version 0.54.0
-- Checking for module 'flux-schedutil'
--   Found flux-schedutil, version 0.54.0
-- Checking for module 'flux-taskmap'
--   Found flux-taskmap, version 0.54.0
-- flux core found and no specific prefix specified, using /usr
CMake Error at CMakeLists.txt:73 (find_package):
  find_package called with invalid argument "3.6...<4.0"


-- Checking for module 'yaml-cpp'
--   Found yaml-cpp, version 0.6.3
-- Checking for module 'libedit'
--   Found libedit, version 3.1
-- Checking for module 'libczmq>=3.0.0'
--   Found libczmq, version 4.2.1
-- Checking for module 'hwloc>=1.11.1'
--   Found hwloc, version 2.4.1
-- Checking for module 'jansson>=2.10'
--   Found jansson, version 2.13.1
-- Checking for module 'uuid'
--   Found uuid, version 2.36.1
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.50") found components: system filesystem graph regex 
-- Boost version: 1.74.0
CMake Error at CMakeLists.txt:122 (message):
  Python module yaml not found or version too low, need 3.10 got
Call Stack (most recent call first):
  CMakeLists.txt:165 (flux_find_python_module)


-- Configuring incomplete, errors occurred!
See also "/nfshome/garlick/proj/flux-sched/CMakeFiles/CMakeOutput.log".
```
Further tries yield shortened output:
```
 garlick@picl0:~/proj/flux-sched$ ./configure
-- VER 0.28.0-60-gcc781dd3
-- Building flux-sched version 0.28.0-60-gcc781dd3
CMake Error at CMakeLists.txt:73 (find_package):
  find_package called with invalid argument "3.6...<4.0"


-- Boost version: 1.74.0
CMake Error at CMakeLists.txt:122 (message):
  Python module yaml not found or version too low, need 3.10 got
Call Stack (most recent call first):
  CMakeLists.txt:165 (flux_find_python_module)


-- Configuring incomplete, errors occurred!
See also "/nfshome/garlick/proj/flux-sched/CMakeFiles/CMakeOutput.log".
```
See also: [CMakeOutput.log](https://github.com/flux-framework/flux-sched/files/12551535/CMakeOutput.log)

### PR DESCRIPTION
**Pull request by trws**
This should fix #1066.

The main changes are:
* Avoid including source files in the `add_library` call for yggdrasil unless the cmake version is 3.19 or higher. Originally I recommended removing them, but that loses information used by some tooling (linters, IDEs, etc.) so now the sources are included if the cmake version is sufficient, and skipped so that building will work with older versions.
* Accept any version of python >=3.6, the range query is only supported in newer versions of cmake and as @grondo pointed out we don't really need that specificity anyway.
* Change the cmake version used by our focal container to 3.18.  That's the closest container we have to debian buster, and rather than make another container seemed like a reasonable target for using the older cmake version.
* In testing this, I ran into a problem with flux-core detection, and added a fix.

### CODE REVIEW

**Comment by grondo** [comment]
Nice! Thanks @trws, this seems to work for me! Perhaps we should get @garlick to test as well.

**Review by grondo — APPROVED** [review]
Works for me!

**Comment by grondo** [comment]
FYI - the `test-install` builds will fail here until flux-framework/flux-core#5453 is merged

**Comment by garlick** [comment]
I got a clean build as well with the default cmake on debian 11.  Thanks!

I do have some  `make check` problems but I'll open a separate issue for that.

**Pull request merged**
