### PR TITLE
NEWS.md: add release notes for v0.9.0

### PR DESCRIPTION
**Pull request by garlick**
Here's a starting point for some v0.9.0 release notes.  Other please feel free to force push to this PR!  I just wanted to get the ball rolling.

### CODE REVIEW

**Comment by garlick** [comment]
BTW all I did here was run the flux-core `relnotes.sh` script, sort the PR's into the bins of (Fixes, Features, Cleanup), combine several flux-tree entries into one entry, and add the little happy note about fluxion re-branding.

It was a pretty quick pass so undoubtedly more could be done to present the changes in a more coherent way.

**Comment by garlick** [comment]
Looking at this again, I did a fairly poor job of sorting entries.  I'll force push a change unless someone else cries "nooo!" quickly.

**Comment by garlick** [comment]
I think we decided we would create this tag after @dongahn makes a quick PR, but before any of the other PR's go in.  I may be offline for a while this afternoon, so if anyone needs to push to this PR to get things moving, I'm totally fine with that.

**Comment by dongahn** [comment]
> I think we decided we would create this tag after @dongahn makes a quick PR, but before any of the other PR's go in.

Just posted the quick PR: https://github.com/flux-framework/flux-sched/pull/676

**Pull request merged**
