### PR TITLE
stop using deprecated flux-core functions

### PR DESCRIPTION
**Pull request by garlick**
This update follows PR flux-framework/flux-core#182.
All changes affected only the simulator.

### CODE REVIEW

**Comment by dongahn** [comment]
Thanks. 

I'm looking at the new scheduler framework service. The only core functionality I am using is flux_event_send for now (i.e., sending resource events and sending wreck run request.)

At some point, @SteVwonder, @lipari  I need to discuss how best we can seamlessly integrate the emulator code as well.

**Comment by grondo** [comment]
Once this is merged I can rebase the work #19.
If we get that PR merged as well, we'll have travis testing support for future PRs

**Comment by garlick** [comment]
@dongahn Let me know if I can help.

**Comment by dongahn** [comment]
@garlick @grondo Thanks. Will do. 

I will try my best to finish up this framework service work ASAP (- "focus mode" now) . Then, I will review @grondo 's change a bit more closely. 

My current thinking:

1 Get #19 reviewed and merged first as the changes will probably be orthogonal to mine. (after getting out of the focus mode) 
2. then I will rebase mine and add a bit of tests before issue a merge request.
3. Once that's done, of course @lipari will merge his RDL replacement branch to this. 

We will probably start to work on the emulator after @SteVwonder starts here (6/1)

**Comment by grondo** [comment]
FYI - Travis build failed because of missing `.travis.yml` in master. Sorry, I thought travis would ignore branches without `.travis.yml`.

@dongahn, if it helps, I can split the testing enhancement from #19 from the RDL code changes and maybe we can get the testing update with travis-ci support merged more quickly, giving you time to review the small RDL update in #19?

**Comment by grondo** [comment]
@dongahn, @lipari : Can we get someone's ACK to merge this PR?
Otherwise, builds against flux-core/master currently fail.
(Probably we should have first merged these changes, *then* merged the flux-core removal of deprecated functions)

**Comment by garlick** [comment]
Apologies for not thinking of that.

**Comment by garlick** [comment]
On merging this: it only affects the simulator code which I think is not the current code @SteVwonder is working with.  Low risk.

**Comment by dongahn** [comment]
Sorry for the delay. Looks good.

**Comment by dongahn** [comment]
FYI -- as discussed this w/ @grondo, he will split #19 into two orthogonal pieces.

**Pull request merged**
