### PR TITLE
plugins: add dlopen RTLD_DEEPBIND flag

### PR DESCRIPTION
**Pull request by garlick**
One step towards fixing #211

### CODE REVIEW

**Comment by grondo** [comment]
Restarted the travis build

**Comment by garlick** [comment]
I had just rerun the gcc build and it failed on the t2002-easy test again.
Anybody from sched have a clue how to diagnose that one?
Everything is running but jobs are not running in the expected order.

**Comment by grondo** [comment]
I ran `t2002-easy.t` test and dumped the job completion times it is using for the compare, and does indeed look like the backfill isn't working, all jobs appear to run in fcfs order... I wonder if the backfill plugin isn't loading correctly?
```

1 1.004068
2 19643.003816
3 28147.004182
4 30566.006998
5 30566.006998
6 77371.003694
7 80090.003604
8 87576.004911
9 88169.003928
10 96589.003074
11 103162.004577
12 126070.003682
expecting success: 
    diff -u ${expected_order} ./actual

--- /home/ubuntu/flux-sched/t/data/emulator-data/easy_expected  2016-08-12 17:05:26.000000000 +0000
+++ ./actual    2016-10-13 23:12:06.869725418 +0000
@@ -1,12 +1,12 @@
 1
 2
 3
+4
+5
 6
 7
 8
 9
 10
 11
-4
-5
 12
not ok 5 - jobs scheduled in correct order
#
#           diff -u ${expected_order} ./actual
#
```

**Comment by garlick** [comment]
Good theory - I'll go poke at that.

Aside: any idea why `flux wreck ls` output is empty when I run it in the test, just after job 12 was verified complete?

**Comment by garlick** [comment]
Well, there is this subtest in `t1004-module-load.t`:
```
test_expect_success 'module-load: sched loads the backfill plugin' '
    flux module load sched.backfill &&
    flux module list sched
'
```

**Comment by dongahn** [comment]
I also saw the same issue (backfill producing FCFS) as part of #191 but we put a temporary fix for that problem...

**Comment by grondo** [comment]
full dmesg output from the test should be in this [gist](https://gist.github.com/20ad27751346d15c3b2f9ac72363e74e)

**Comment by grondo** [comment]
> Aside: any idea why flux wreck ls output is empty when I run it in the test, just after job 12 was verified complete?

No ... what does `flux kvs dir lwj` return?

**Comment by garlick** [comment]
> what does flux kvs dir lwj return?

```
lwj.1 -> lwj-active.1
lwj.2 -> lwj-active.2
lwj.3 -> lwj-active.3
lwj.4 -> lwj-active.4
lwj.5 -> lwj-active.5
lwj.6 -> lwj-active.6
lwj.7 -> lwj-active.7
lwj.8 -> lwj-active.8
lwj.9 -> lwj-active.9
lwj.10 -> lwj-active.10
lwj.11 -> lwj-active.11
lwj.12 -> lwj-active.12
```

**Comment by grondo** [comment]
are you running with the test with `-d -v`? when I run I get the following error, because the lwj entries don't appear to be "real" jobs:
```
lua: /tmp/inst/libexec/flux/cmd/flux-wreck:213: attempt to index field 'cmdline' (a nil value)
stack traceback:
        /tmp/inst/libexec/flux/cmd/flux-wreck:213: in function </tmp/inst/libexec/flux/cmd/flux-wreck:185>
        /tmp/inst/libexec/flux/cmd/flux-wreck:248: in function 'handler'
        /tmp/inst/share/lua/5.1/flux/Subcommander.lua:146: in function </tmp/inst/share/lua/5.1/flux/Subcommander.lua:127>
        (tail call): ?
        /tmp/inst/libexec/flux/cmd/flux-wreck:397: in main chunk
        [C]: ?
```

**Comment by garlick** [comment]
Oh, I missed that.  Yes I see that too.

**Comment by garlick** [comment]
> I wonder if the backfill plugin isn't loading correctly?

Inserted a `flux-module list sched` and it is indeed loaded:
```
Module               Size    Digest  Idle  S  Nodeset
sched.backfill        258048 2D73E4E    0  R  0
```
The dmesg in the gist shows a successful load also.

**Comment by garlick** [comment]
It sounds like we might need @SteVwonder to have a look here, if the problem is similar to #191.

@grondo had a good idea.  Since "sched's dead" because of the json problems I introduced, maybe we should temporarily disable this test in this PR, get sched passing travis again, then come back to this?

**Comment by garlick** [comment]
OK, I propose we merge this.  Sorry everyone for the trouble that json change caused!

**Comment by dongahn** [comment]
From [gist](https://gist.github.com/anonymous/20ad27751346d15c3b2f9ac72363e74e), there seems to be something else going on than backfill scheduling FCFS. The trace is at least missing some jobs like job (2) etc. Don't know how this could affect that behavior, though.

**Comment by dongahn** [comment]
OK. Merging this and let's have @SteVwonder take a look at the emulator test cases.

**Pull request merged**
