### PR TITLE
Add release notes for v0.35.0

### PR DESCRIPTION
**Pull request by grondo**
Thought I'd get a `NEWS.md` update ready for the upcoming sched release.

Feel free to push directly here with updates or modifications.

### CODE REVIEW

**Comment by trws** [comment]
Ok, as soon as we manage to land #1217 I think we'll be good to go.  Anything else you want to make sure happens @milroy?

**Comment by milroy** [comment]
> Anything else you want to make sure happens @milroy?

Nope, I think PR #1217 is the last one we need.

**Comment by grondo** [comment]
I'll squash and update this PR now

**Comment by grondo** [comment]
Done. If this gets a review then we can set MWP and then I (or whoever) can push the tag.

**Review by trws — APPROVED** [review]

**Pull request merged**
