### PR TITLE
NEWS.md: update for flux-sched v0.6.0

### PR DESCRIPTION
**Pull request by SteVwonder**
Add a NEWS entry for v0.6.0 before tagging the release.

### CODE REVIEW

**Comment by grondo** [comment]
I wanted to get lua 5.2 fixes into this release, but it seems like I'm not going to get that done too quickly, so otherwise 0.6.0 is ready?

**Comment by SteVwonder** [comment]
>  I  wanted to get lua 5.2 fixes into this release, but it seems like I'm  not going to get that done too quickly, so otherwise 0.6.0 is ready?

I totally forgot about the lua5.2 fixes.  I'm fine waiting for them.

**Comment by dongahn** [comment]
Otherwise, LGTM! Thanks @grondo and @StevWonder.

**Comment by SteVwonder** [comment]
Are we waiting on anything else before tagging 0.6.0 or was #373 the last thing?

**Comment by grondo** [comment]
That was the last thing I had anyway. Sorry it took a bit of time...

**Comment by SteVwonder** [comment]
> That was the last thing I had anyway.

Ok.  I just rebased and added the lua 5.2 support to the release notes.  Should be ready to merge.

>Sorry it took a bit of time...

No worries.  Definitely worth the wait!  Thanks again @grondo!

**Comment by SteVwonder** [comment]
Hmmm.  I don't think I have ever seen this one before:
```
[0;31mFAIL[m: t5000-valgrind.t 2 - valgrind reports no new errors on single broker run
[0;35mERROR[m: t5000-valgrind.t - exited with status 1
[0;31m============================================================================[m
[0;31mTestsuite summary for flux-sched 0.5.0-49-g705fb7f[m
[0;31m============================================================================[m
[1m# TOTAL: 298[m
[0;32m# PASS:  288[m
[1;34m# SKIP:  7[m
[1;32m# XFAIL: 1[m
[0;31m# FAIL:  1[m
# XPASS: 0
[0;35m# ERROR: 1[m
[0;31m============================================================================[m
[0;31mSee t/test-suite.log[m
[0;31m============================================================================[m
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/travis/build/flux-framework/flux-sched/t'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/travis/build/flux-framework/flux-sched/t'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/travis/build/flux-framework/flux-sched/t'
make: *** [check-recursive] Error 1

travis_time:end:1e7b37b6:start=1533254546471001595,finish=1533254833076543980,duration=286605542385
[0K
[31;1mThe command "autoreconf -i && ./configure ${ARGS} && echo $MAKECMDS && eval ${MAKECMDS}" exited with 2.[0m
travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:126e3100
[0K
travis_time:end:126e3100:start=1533254833081086283,finish=1533254833084662301,duration=3576018
[0Ktravis_time:start:02efbbac
[0K[32;1mchanges detected, packing new archive[0m
.
[32;1muploading archive[0m

travis_time:end:02efbbac:start=1533254833088632635,finish=1533254848166785760,duration=15078153125
[0Ktravis_fold:end:cache.2
[0Ktravis_fold:start:after_failure.1
[0Ktravis_time:start:0275c43c
[0K$ find . -name t[0-9]*.output -print0 | xargs -0 -I'{}' sh -c 'printf "\033[31mFound {}\033[39m\n";cat {}'
[31mFound ./t/t5000-valgrind.output[39m
expecting success: 
	echo "found broker at ${BROKER}" >&2 &&
	test -x "$BROKER"

found broker at /home/travis/local2/libexec/flux/cmd/flux-broker
ok 1 - found executable flux-broker
found executable flux-broker

expecting success: 
	flux ${VALGRIND} \
		--tool=memcheck \
		--leak-check=full \
		--gen-suppressions=all \
		--trace-children=no \
		--child-silent-after-fork=yes \
		--num-callers=30 \
		--leak-resolution=med \
		--error-exitcode=1 \
		--suppressions=$VALGRIND_SUPPRESSIONS \
		${BROKER} --shutdown-grace=4 ${VALGRIND_WORKLOAD} 10

==122038== Memcheck, a memory error detector
==122038== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==122038== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==122038== Command: /home/travis/local2/libexec/flux/cmd/flux-broker --shutdown-grace=4 /home/travis/build/flux-framework/flux-sched/t/valgrind/valgrind-workload.sh 10
==122038== 
****************************************************************************
* hwloc 1.11.1 has encountered what looks like an error from the operating system.
*
* L3 (cpuset 0x00001000,0x02100002) intersects with NUMANode (P#0 cpuset 0x00001111,0x11111111) without inclusion!
* Error occurred in topology.c line 981
*
* The following FAQ entry in the hwloc documentation may help:
*   What should I do when hwloc reports "operating system" warnings?
* Otherwise please report this error message to the hwloc user's mailing list,
* along with the output+tarball generated by the hwloc-gather-topology script.
****************************************************************************
FLUX_URI=local:///tmp/flux-2otYrl
==122038== 
==122038== HEAP SUMMARY:
==122038==     in use at exit: 116,663 bytes in 131 blocks
==122038==   total heap usage: 1,039,748 allocs, 1,039,617 frees, 93,693,867 bytes allocated
==122038== 
==122038== 288 bytes in 1 blocks are possibly lost in loss record 33 of 46
==122038==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==122038==    by 0x4012EE4: allocate_dtv (dl-tls.c:296)
==122038==    by 0x4012EE4: _dl_allocate_tls (dl-tls.c:460)
==122038==    by 0x59D5D92: allocate_stack (allocatestack.c:589)
==122038==    by 0x59D5D92: pthread_create@@GLIBC_2.2.5 (pthread_create.c:500)
==122038==    by 0x52CA8DA: zactor_new (zactor.c:122)
==122038==    by 0x4E54F75: flux_sec_comms_init (security.c:197)
==122038==    by 0x40D674: overlay_sec_init (overlay.c:572)
==122038==    by 0x40D674: overlay_bind (overlay.c:611)
==122038==    by 0x415A61: boot_pmi (boot_pmi.c:285)
==122038==    by 0x407864: main (broker.c:463)
==122038== 
{
   <insert_a_suppression_name_here>
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   fun:allocate_dtv
   fun:_dl_allocate_tls
   fun:allocate_stack
   fun:pthread_create@@GLIBC_2.2.5
   fun:zactor_new
   fun:flux_sec_comms_init
   fun:overlay_sec_init
   fun:overlay_bind
   fun:boot_pmi
   fun:main
}
==122038== LEAK SUMMARY:
==122038==    definitely lost: 0 bytes in 0 blocks
==122038==    indirectly lost: 0 bytes in 0 blocks
==122038==      possibly lost: 288 bytes in 1 blocks
==122038==    still reachable: 115,863 bytes in 129 blocks
==122038==         suppressed: 512 bytes in 1 blocks
==122038== Reachable blocks (those to which a pointer was found) are not shown.
==122038== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==122038== 
==122038== For counts of detected and suppressed errors, rerun with: -v
==122038== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 1 from 1)
not ok 2 - valgrind reports no new errors on single broker run
```

Hopefully it is just transient.  Restarting the job.

**Comment by grondo** [comment]
Failed this time with
```
not ok 8 - rs2rank: can schedule GPUs using hwloc
```
https://api.travis-ci.org/v3/job/411525688/log.txt

I wonder if the test was just slow?

Restarted since all the other builders completed successfully.

**Comment by grondo** [comment]
Failed once again with the above error (or somehow *I* failed to restart). Someone may want to examine that rs2rank test for race conditions, but otherwise the third time the test restarted it passed.

@SteVwonder, it is minor, but we may want to update the date on the NEWS.md entry.

**Comment by SteVwonder** [comment]
@grondo: good call.  The date has been updated.

**Comment by SteVwonder** [comment]
Following up on the hwloc error from before, it seems that the hwloc documentation blames the OS/hardware for returning erroneous results: https://www.open-mpi.org/projects/hwloc/doc/v1.11.2/a00030.php#faq_os_error

So maybe we can just blame that one on Travis?

As for the other one, unfortunately, the failing job's log was overwritten by the restart.  Do you remember if there was any other output that could narrow down the problem?

**Comment by grondo** [comment]
Oh, sorry, I thought Travis kept logs from restarted builds!

I looked at the verbose output and there wasn't an obvious error. Let me look back in my older browser tabs and see if I still have the full text

**Pull request merged**
